// Single-mode text-to-video and image-to-video models on kie.ai
// (Kling 2.x/3.0 Turbo/Omni, Hailuo, MiniMax H3, Grok Imagine, Wan 2.x,
// Seedance 1.0, HappyHorse, PixVerse). Control keys for pre-catalog models are
// kept as they were so saved generations and presets still regenerate correctly.

import type { FieldSpec, MediaSlot, ModelSpec, Pricing } from './types.ts';
import { negativePrompt, opts, ratio, seconds, seedField } from './helpers.ts';

/** Integer duration slider (sent as a number unless `cast` says otherwise). */
const durationRange = (min: number, max: number, def: number, cast: 'string' | 'number' = 'number'): FieldSpec => ({
  key: 'duration', label: 'Duration', type: 'number', min, max, step: 1, default: def, cast, help: `${min}–${max} seconds.`,
});

/** Single-URL image slot (`image_url`, `end_image_url`, `first_frame_url`…). */
const frame = (key: 'start_frame' | 'end_frame', api: string, required: boolean, help?: string): MediaSlot => ({
  key, api, kind: 'image', label: key === 'start_frame' ? 'Start frame' : 'End frame', max: 1, single: true,
  ...(required ? { min: 1 } : {}), ...(help ? { help } : {}),
});

const promptExtend = (key: string, def: boolean): FieldSpec => ({
  key, label: 'Prompt expansion', type: 'boolean', default: def, advanced: true, help: 'Let the model rewrite short prompts into a fuller description.',
});

// ─── Kling ───────────────────────────────────────────────────────────────────
const klingCfg: FieldSpec = {
  key: 'cfg_scale', label: 'Prompt adherence', type: 'number', min: 0, max: 1, step: 0.1, default: 0.5, advanced: true,
  help: 'Higher follows the prompt more literally (CFG scale).',
};
const klingRatio = (def = '16:9') => ratio('aspectRatio', ['16:9', '9:16', '1:1'], def);
const klingSound: FieldSpec = { key: 'sound', label: 'Native audio', type: 'boolean', default: false, help: 'Dialogue, sound effects and ambience generated with the video.' };
const klingTurboPricing: Pricing = { by: 'resolution', table: { '720p': 18, '1080p': 22.5 }, perSecond: 'duration' };
const klingOmniFields: FieldSpec[] = [
  {
    key: 'resolution', label: 'Resolution', type: 'enum', default: '720p',
    options: [{ value: '720p', label: '720p' }, { value: '1080p', label: '1080p' }, { value: '4k', label: '4K' }],
  },
  durationRange(3, 15, 5),
  { key: 'audio', label: 'Native audio', type: 'boolean', default: false, help: 'Dialogue, sound effects and ambience generated with the video.' },
];
// price unverified — Kling 3.0 Omni is not in the pricing feed; using Kling 3.0 per-second rates
const klingOmniPricing: Pricing = {
  by: ['resolution', 'audio'],
  table: { '720p|false': 14, '720p|true': 20, '1080p|false': 18, '1080p|true': 27, '4k|false': 67, '4k|true': 67 },
  perSecond: 'duration',
};

// ─── Hailuo / MiniMax ────────────────────────────────────────────────────────
const hailuoOptimizer: FieldSpec = {
  key: 'prompt_optimizer', label: 'Prompt optimizer', type: 'boolean', default: true, advanced: true, help: 'Let MiniMax refine the prompt before generating.',
};
const hailuo23Fields: FieldSpec[] = [
  { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('768P', '1080P'), default: '768P' },
  { ...seconds([6, 10], 6), when: { key: 'resolution', in: ['768P'] }, help: '10s is only available at 768P.' },
];
const h3Resolution: FieldSpec = {
  key: 'resolution', label: 'Resolution', type: 'enum', default: '2K', options: [{ value: '768P', label: '768p' }, { value: '2K', label: '2K' }],
};
const h3Pricing: Pricing = { by: 'resolution', table: { '768P': 8, '2K': 13 }, perSecond: 'duration' };

// ─── Seedance 1.0 ────────────────────────────────────────────────────────────
const seedance1Res = (values = ['480p', '720p', '1080p']): FieldSpec => ({
  key: 'resolution', label: 'Resolution', type: 'enum', options: opts(...values), default: '720p',
});
const cameraFixed: FieldSpec = { key: 'camera_fixed', label: 'Lock camera', type: 'boolean', default: false, help: 'Keep the camera static — only the subject moves.' };
const safetyChecker: FieldSpec = { key: 'enable_safety_checker', label: 'Safety checker', type: 'boolean', default: true, advanced: true };
// price unverified — Seedance 1.0 is not in the pricing feed; using Seedance 1.5 Pro (no audio) per-second rates rounded up
const seedance1Pricing: Pricing = { by: 'resolution', table: { '480p': 2, '720p': 4, '1080p': 8 }, perSecond: 'duration' };

// ─── Grok Imagine ────────────────────────────────────────────────────────────
const grokRatio = (def: string): FieldSpec => ratio('aspectRatio', ['2:3', '3:2', '1:1', '16:9', '9:16'], def);
const grokResolution: FieldSpec = { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('480p', '720p', '1080p'), default: '480p' };
const grokPricing: Pricing = { by: 'resolution', table: { '480p': 2.4, '720p': 4.5, '1080p': 8 }, perSecond: 'duration' };

// ─── Wan ─────────────────────────────────────────────────────────────────────
const wanRes1080: FieldSpec = { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('720p', '1080p'), default: '1080p' };
const wanWatermark: FieldSpec = { key: 'watermark', label: 'Watermark', type: 'boolean', default: false, advanced: true };
const wan27Pricing: Pricing = { by: 'resolution', table: { '720p': 16, '1080p': 24 }, perSecond: 'duration' };
const wan26MultiShots: FieldSpec = {
  key: 'wan_multi_shots', api: 'multi_shots', label: 'Multi-shot', type: 'boolean', default: false,
  help: 'Let the model cut the clip into several shots.',
};
const wan26Pricing: Pricing = {
  by: ['resolution', 'duration'],
  table: { '720p|5': 70, '720p|10': 140, '720p|15': 210, '1080p|5': 104.5, '1080p|10': 209.5, '1080p|15': 315 },
};
const wan25Pricing: Pricing = { by: ['resolution', 'duration'], table: { '720p|5': 60, '720p|10': 120, '1080p|5': 100, '1080p|10': 200 } };
const wan22Fields: FieldSpec[] = [
  { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('480p', '720p'), default: '720p' },
  promptExtend('enable_prompt_expansion', false),
  {
    key: 'acceleration', label: 'Acceleration', type: 'enum', default: 'none', advanced: true,
    options: [{ value: 'none', label: 'Off (best quality)' }, { value: 'regular', label: 'Regular (faster)' }],
  },
  seedField(),
];
const wan22Pricing: Pricing = { by: 'resolution', table: { '480p': 40, '720p': 80 } };

// ─── HappyHorse ──────────────────────────────────────────────────────────────
const hhPricing10: Pricing = { by: 'resolution', table: { '720p': 28, '1080p': 48 }, perSecond: 'duration' };
const hhPricing11: Pricing = { by: 'resolution', table: { '720p': 22.5, '1080p': 29 }, perSecond: 'duration' };

// ─── PixVerse V6 ─────────────────────────────────────────────────────────────
const pixverseFields: FieldSpec[] = [
  { key: 'quality', label: 'Resolution', type: 'enum', options: opts('360p', '540p', '720p', '1080p'), default: '720p' },
  durationRange(1, 15, 5),
  { key: 'generate_audio_switch', label: 'Native audio', type: 'boolean', default: false, help: 'Sound effects and ambience generated with the video.' },
  seedField(),
];
const pixverseMultiClip: FieldSpec = {
  key: 'generate_multi_clip_switch', label: 'Multi-clip', type: 'boolean', default: false, help: 'Let the model cut the clip into several shots.',
};
const pixversePricing: Pricing = {
  by: ['quality', 'generate_audio_switch'],
  table: {
    '360p|false': 4, '540p|false': 5.6, '720p|false': 7.2, '1080p|false': 14.4,
    '360p|true': 5.6, '540p|true': 7.2, '720p|true': 9.6, '1080p|true': 18.4,
  },
  perSecond: 'duration',
};

export const VIDEO_CLASSIC_SPECS: ModelSpec[] = [
  // ─── Kuaishou · Kling ──────────────────────────────────────────────────────
  {
    id: 'kling-3.0-turbo',
    family: 'kling',
    name: 'Kling 3.0 Turbo',
    provider: 'Kuaishou',
    mode: 'text-to-video',
    bestFor: 'Kling 3.0 motion quality at a lower price when you do not need audio, multi-shot or 4K.',
    tags: ['1080p', 'Up to 15s', 'Fast'],
    api: 'market',
    kieModel: 'kling/v3-turbo-text-to-video',
    output: 'video',
    promptMax: 2500,
    fields: [
      klingRatio(),
      { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('720p', '1080p'), default: '720p' },
      seconds([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 5),
    ],
    media: [],
    pricing: klingTurboPricing,
    isNew: true,
  },
  {
    id: 'kling-3.0-turbo-i2v',
    family: 'kling',
    name: 'Kling 3.0 Turbo',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Animating a single image with Kling 3.0 motion, cheaper than full Kling 3.0.',
    tags: ['1080p', 'Up to 15s', 'Fast'],
    api: 'market',
    kieModel: 'kling/v3-turbo-image-to-video',
    output: 'video',
    promptMax: 2500,
    fields: [
      { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('720p', '1080p'), default: '720p' },
      seconds([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 5),
    ],
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: 'JPG/PNG up to 10MB.' }],
    pricing: klingTurboPricing,
    isNew: true,
  },
  {
    id: 'kling-3.0-omni',
    family: 'kling',
    name: 'Kling 3.0 Omni',
    provider: 'Kuaishou',
    mode: 'text-to-video',
    bestFor: 'Kling 3.0 Omni text-to-video with native audio and up to 4K for polished single-take scenes.',
    tags: ['Native audio', '4K', 'Up to 15s'],
    api: 'market',
    kieModel: 'kling-3.0-omni/text-to-video',
    output: 'video',
    audio: true,
    promptMax: 3072,
    fields: [klingRatio(), ...klingOmniFields],
    media: [],
    pricing: klingOmniPricing,
    isNew: true,
  },
  {
    id: 'kling-3.0-omni-i2v',
    family: 'kling',
    name: 'Kling 3.0 Omni',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Start → end frame animation with native audio and up to 4K, keeping the image’s framing.',
    tags: ['Start + end frame', 'Native audio', '4K'],
    api: 'market',
    kieModel: 'kling-3.0-omni/image-to-video',
    output: 'video',
    audio: true,
    promptMax: 3072,
    fields: klingOmniFields,
    media: [
      { key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: 'JPG/PNG up to 50MB, ≥300px, aspect 0.4–2.5.' },
      { key: 'end_frame', api: 'image_urls', kind: 'image', label: 'End frame', max: 1, help: 'Optional — the clip ends on this image.' },
    ],
    // Single-take frame mode: aspect ratio follows the input image ("auto").
    fixed: { customize_multi_shots: false },
    pricing: klingOmniPricing,
    isNew: true,
  },
  {
    id: 'kling-2.6',
    family: 'kling',
    name: 'Kling 2.6',
    provider: 'Kuaishou',
    mode: 'text-to-video',
    bestFor: 'Short 5–10s clips with optional synced dialogue and sound effects from a text prompt.',
    tags: ['Native audio', '5s / 10s'],
    api: 'market',
    kieModel: 'kling-2.6/text-to-video',
    output: 'video',
    audio: true,
    promptMax: 1000,
    fields: [klingRatio('1:1'), seconds([5, 10], 5), klingSound],
    media: [],
    pricing: { by: ['duration', 'sound'], table: { '5|false': 55, '5|true': 110, '10|false': 110, '10|true': 220 } },
  },
  {
    id: 'kling-2.6-i2v',
    family: 'kling',
    name: 'Kling 2.6',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Bringing a photo to life with matching dialogue or sound effects in 5 or 10 seconds.',
    tags: ['Native audio', '5s / 10s'],
    api: 'market',
    kieModel: 'kling-2.6/image-to-video',
    output: 'video',
    audio: true,
    promptMax: 1000,
    fields: [seconds([5, 10], 5), klingSound],
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: 'JPG/PNG up to 10MB.' }],
    pricing: { by: ['duration', 'sound'], table: { '5|false': 55, '5|true': 110, '10|false': 110, '10|true': 220 } },
  },
  {
    id: 'kling-2.5-turbo',
    family: 'kling',
    name: 'Kling 2.5 Turbo Pro',
    provider: 'Kuaishou',
    mode: 'text-to-video',
    bestFor: 'Dynamic action and camera moves at mid-range cost — a good silent-clip workhorse.',
    tags: ['1080p', '5s / 10s'],
    api: 'market',
    kieModel: 'kling/v2-5-turbo-text-to-video-pro',
    output: 'video',
    promptMax: 2500,
    fields: [klingRatio(), seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [],
    pricing: { by: 'duration', table: { 5: 42, 10: 84 } },
  },
  {
    id: 'kling-2.5-turbo-i2v',
    family: 'kling',
    name: 'Kling 2.5 Turbo Pro',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Affordable start → end frame animation with strong motion for product and action shots.',
    tags: ['Start + end frame', '1080p'],
    api: 'market',
    kieModel: 'kling/v2-5-turbo-image-to-video-pro',
    output: 'video',
    promptMax: 2500,
    fields: [seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [
      frame('start_frame', 'image_url', true, 'JPG/PNG up to 10MB.'),
      frame('end_frame', 'tail_image_url', false, 'Optional — the clip ends on this image.'),
    ],
    pricing: { by: 'duration', table: { 5: 42, 10: 84 } },
  },
  {
    id: 'kling-2.1-master',
    family: 'kling',
    name: 'Kling 2.1 Master',
    provider: 'Kuaishou',
    mode: 'text-to-video',
    bestFor: 'Top-tier Kling 2.1 quality for hero shots where motion fidelity matters more than price.',
    tags: ['1080p', 'Premium'],
    api: 'market',
    kieModel: 'kling/v2-1-master-text-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [klingRatio(), seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [],
    pricing: { by: 'duration', table: { 5: 160, 10: 320 } },
  },
  {
    id: 'kling-2.1-master-i2v',
    family: 'kling',
    name: 'Kling 2.1 Master',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Highest-fidelity Kling 2.1 animation of a single image for premium hero shots.',
    tags: ['1080p', 'Premium'],
    api: 'market',
    kieModel: 'kling/v2-1-master-image-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [frame('start_frame', 'image_url', true, 'JPG/PNG up to 10MB.')],
    pricing: { by: 'duration', table: { 5: 160, 10: 320 } },
  },
  {
    id: 'kling-2.1-pro-i2v',
    family: 'kling',
    name: 'Kling 2.1 Pro',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: '1080p image animation with an optional end frame — mid-price between Standard and Master.',
    tags: ['Start + end frame', '1080p'],
    api: 'market',
    kieModel: 'kling/v2-1-pro',
    output: 'video',
    promptMax: 5000,
    fields: [seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [
      frame('start_frame', 'image_url', true, 'JPG/PNG up to 10MB.'),
      frame('end_frame', 'tail_image_url', false, 'Optional — the clip ends on this image.'),
    ],
    pricing: { by: 'duration', table: { 5: 50, 10: 100 } },
  },
  {
    id: 'kling-2.1-standard-i2v',
    family: 'kling',
    name: 'Kling 2.1 Standard',
    provider: 'Kuaishou',
    mode: 'image-to-video',
    bestFor: 'Cheapest Kling option for quick 720p animations of a single image.',
    tags: ['720p', 'Budget'],
    api: 'market',
    kieModel: 'kling/v2-1-standard',
    output: 'video',
    promptMax: 5000,
    fields: [seconds([5, 10], 5), negativePrompt(), klingCfg],
    media: [frame('start_frame', 'image_url', true, 'JPG/PNG up to 10MB.')],
    pricing: { by: 'duration', table: { 5: 25, 10: 50 } },
  },

  // ─── MiniMax · H3 + Hailuo ────────────────────────────────────────────────
  {
    id: 'minimax-h3',
    family: 'minimax',
    name: 'MiniMax H3',
    provider: 'MiniMax',
    mode: 'text-to-video',
    bestFor: 'Long, detailed prompts turned into sharp 2K clips up to 15s with strong scene direction.',
    tags: ['2K', 'Up to 15s', 'Long prompts'],
    api: 'market',
    kieModel: 'minimax-h3/text-to-video',
    output: 'video',
    promptMax: 7000,
    fields: [ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'], '16:9'), h3Resolution, durationRange(4, 15, 6)],
    media: [],
    pricing: h3Pricing,
    featured: true,
    isNew: true,
  },
  {
    id: 'minimax-h3-i2v',
    family: 'minimax',
    name: 'MiniMax H3',
    provider: 'MiniMax',
    mode: 'image-to-video',
    bestFor: '2K first → last frame animation up to 15s for smooth, controlled transitions.',
    tags: ['Start + end frame', '2K', 'Up to 15s'],
    api: 'market',
    kieModel: 'minimax-h3/image-to-video',
    output: 'video',
    promptMax: 7000,
    fields: [h3Resolution, durationRange(4, 15, 6)],
    media: [
      frame('start_frame', 'first_frame_url', true, 'JPG/PNG/WebP/HEIC up to 30MB, 256–5760px, aspect 0.4–2.5.'),
      frame('end_frame', 'last_frame_url', false, 'Optional — the clip ends on this image.'),
    ],
    // price unverified — the feed also bills 4 credits per input image, which this table cannot add
    pricing: h3Pricing,
    featured: true,
    isNew: true,
  },
  {
    id: 'hailuo-02-pro',
    family: 'hailuo',
    name: 'Hailuo 02 Pro',
    provider: 'MiniMax',
    mode: 'text-to-video',
    bestFor: 'Physics-heavy action (sports, stunts, crashes) in 1080p — pick over Standard for sharper detail.',
    tags: ['1080p', 'Physics', '6s'],
    api: 'market',
    kieModel: 'hailuo/02-text-to-video-pro',
    output: 'video',
    promptMax: 1500,
    fields: [hailuoOptimizer],
    media: [],
    pricing: { credits: 57 },
  },
  {
    id: 'hailuo-02-standard',
    family: 'hailuo',
    name: 'Hailuo 02 Standard',
    provider: 'MiniMax',
    mode: 'text-to-video',
    bestFor: 'Budget 768p clips with realistic physics, and 10s length that Pro does not offer.',
    tags: ['768p', 'Budget', '6s / 10s'],
    api: 'market',
    kieModel: 'hailuo/02-text-to-video-standard',
    output: 'video',
    promptMax: 1500,
    fields: [seconds([6, 10], 6), hailuoOptimizer],
    media: [],
    pricing: { by: 'duration', table: { 6: 30, 10: 50 } },
  },
  {
    id: 'hailuo-2.3-pro-i2v',
    family: 'hailuo',
    name: 'Hailuo 2.3 Pro',
    provider: 'MiniMax',
    mode: 'image-to-video',
    bestFor: 'Expressive character acting and dance from a photo, with the best Hailuo detail up to 1080p.',
    tags: ['1080p', 'Characters'],
    api: 'market',
    kieModel: 'hailuo/2-3-image-to-video-pro',
    output: 'video',
    promptMax: 5000,
    fields: hailuo23Fields,
    media: [frame('start_frame', 'image_url', true)],
    // fallback: 10s is not offered at 1080P, so the clip is billed as 6s
    pricing: { by: ['resolution', 'duration'], table: { '768P|6': 45, '768P|10': 90, '1080P|6': 80 }, fallback: 80 },
    featured: true,
  },
  {
    id: 'hailuo-2.3-standard-i2v',
    family: 'hailuo',
    name: 'Hailuo 2.3 Standard',
    provider: 'MiniMax',
    mode: 'image-to-video',
    bestFor: 'Cheaper Hailuo 2.3 character animation from a photo when Pro detail is not needed.',
    tags: ['1080p', 'Budget'],
    api: 'market',
    kieModel: 'hailuo/2-3-image-to-video-standard',
    output: 'video',
    promptMax: 5000,
    fields: hailuo23Fields,
    media: [frame('start_frame', 'image_url', true)],
    // fallback: 10s is not offered at 1080P, so the clip is billed as 6s
    pricing: { by: ['resolution', 'duration'], table: { '768P|6': 30, '768P|10': 50, '1080P|6': 50 }, fallback: 50 },
  },
  {
    id: 'hailuo-02-pro-i2v',
    family: 'hailuo',
    name: 'Hailuo 02 Pro',
    provider: 'MiniMax',
    mode: 'image-to-video',
    bestFor: '1080p start → end frame animation with realistic physics for action beats.',
    tags: ['Start + end frame', '1080p', '6s'],
    api: 'market',
    kieModel: 'hailuo/02-image-to-video-pro',
    output: 'video',
    promptMax: 1500,
    fields: [hailuoOptimizer],
    media: [
      frame('start_frame', 'image_url', true, 'Up to 10MB.'),
      frame('end_frame', 'end_image_url', false, 'Optional — the clip ends on this image.'),
    ],
    pricing: { credits: 57 },
  },
  {
    id: 'hailuo-02-standard-i2v',
    family: 'hailuo',
    name: 'Hailuo 02 Standard',
    provider: 'MiniMax',
    mode: 'image-to-video',
    bestFor: 'Low-cost start → end frame animation; 512p drafts from 12 credits before a final render.',
    tags: ['Start + end frame', 'Budget', '512p / 768p'],
    api: 'market',
    kieModel: 'hailuo/02-image-to-video-standard',
    output: 'video',
    promptMax: 1500,
    fields: [
      { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('512P', '768P'), default: '768P' },
      seconds([6, 10], 10),
      hailuoOptimizer,
    ],
    media: [
      frame('start_frame', 'image_url', true, 'Up to 10MB.'),
      frame('end_frame', 'end_image_url', false, 'Optional — the clip ends on this image.'),
    ],
    // price unverified — no 768P 6s row in the feed; using Hailuo 02 Standard T2V 768p 6s (30)
    pricing: { by: ['resolution', 'duration'], table: { '512P|6': 12, '512P|10': 20, '768P|6': 30, '768P|10': 50 } },
  },

  // ─── ByteDance · Seedance 1.0 ─────────────────────────────────────────────
  {
    id: 'seedance-1.0-pro',
    family: 'seedance-1',
    name: 'Seedance 1.0 Pro',
    provider: 'ByteDance',
    mode: 'text-to-video',
    bestFor: 'Multi-shot cinematic cuts from one prompt at 1080p, with a lockable camera.',
    tags: ['Multi-shot', '1080p', 'Silent'],
    api: 'market',
    kieModel: 'bytedance/v1-pro-text-to-video',
    output: 'video',
    promptMax: 10000,
    fields: [
      ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'], '16:9'),
      seedance1Res(),
      seconds([5, 10], 5),
      cameraFixed,
      seedField(),
      safetyChecker,
    ],
    media: [],
    pricing: seedance1Pricing,
  },
  {
    id: 'seedance-1.0-lite',
    family: 'seedance-1',
    name: 'Seedance 1.0 Lite',
    provider: 'ByteDance',
    mode: 'text-to-video',
    bestFor: 'Quick, low-cost Seedance drafts to test a prompt before rendering with Pro.',
    tags: ['Budget', 'Silent'],
    api: 'market',
    kieModel: 'bytedance/v1-lite-text-to-video',
    output: 'video',
    promptMax: 10000,
    fields: [
      ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4', '9:21'], '16:9'),
      seedance1Res(),
      seconds([5, 10], 5),
      cameraFixed,
      seedField(),
      safetyChecker,
    ],
    media: [],
    pricing: seedance1Pricing,
  },
  {
    id: 'seedance-1.0-pro-i2v',
    family: 'seedance-1',
    name: 'Seedance 1.0 Pro',
    provider: 'ByteDance',
    mode: 'image-to-video',
    bestFor: 'Faithful 1080p animation of a photo with multi-shot cuts and optional locked camera.',
    tags: ['Multi-shot', '1080p', 'Silent'],
    api: 'market',
    kieModel: 'bytedance/v1-pro-image-to-video',
    output: 'video',
    promptMax: 10000,
    fields: [seedance1Res(), seconds([5, 10], 5), cameraFixed, seedField(), safetyChecker],
    media: [frame('start_frame', 'image_url', true, 'Up to 10MB.')],
    pricing: seedance1Pricing,
  },
  {
    id: 'seedance-1.0-pro-fast-i2v',
    family: 'seedance-1',
    name: 'Seedance 1.0 Pro Fast',
    provider: 'ByteDance',
    mode: 'image-to-video',
    bestFor: 'Faster Seedance Pro image animation for quick 720p/1080p turnarounds.',
    tags: ['Fast', '1080p', 'Silent'],
    api: 'market',
    kieModel: 'bytedance/v1-pro-fast-image-to-video',
    output: 'video',
    promptMax: 10000,
    fields: [seedance1Res(['720p', '1080p']), seconds([5, 10], 5)],
    media: [frame('start_frame', 'image_url', true, 'Up to 10MB.')],
    pricing: seedance1Pricing,
  },
  {
    id: 'seedance-1.0-lite-i2v',
    family: 'seedance-1',
    name: 'Seedance 1.0 Lite',
    provider: 'ByteDance',
    mode: 'image-to-video',
    bestFor: 'Budget first → last frame animation for drafts and simple transitions.',
    tags: ['Start + end frame', 'Budget', 'Silent'],
    api: 'market',
    kieModel: 'bytedance/v1-lite-image-to-video',
    output: 'video',
    promptMax: 10000,
    fields: [seedance1Res(), seconds([5, 10], 5), cameraFixed, seedField(), safetyChecker],
    media: [
      frame('start_frame', 'image_url', true, 'Up to 10MB.'),
      frame('end_frame', 'end_image_url', false, 'Optional — the clip ends on this image.'),
    ],
    pricing: seedance1Pricing,
  },

  // ─── Alibaba · Wan ────────────────────────────────────────────────────────
  {
    id: 'wan-2.7',
    family: 'wan',
    name: 'Wan 2.7',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: '1080p clips up to 15s that can follow your own audio track for music-synced visuals.',
    tags: ['1080p', 'Up to 15s', 'Audio-driven'],
    api: 'market',
    kieModel: 'wan/2-7-text-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [
      ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4'], '16:9', 'ratio'),
      wanRes1080,
      durationRange(2, 15, 5),
      negativePrompt(),
      promptExtend('prompt_extend', true),
      wanWatermark,
      seedField(),
    ],
    media: [{ key: 'audio', api: 'audio_url', kind: 'audio', label: 'Audio', max: 1, single: true, help: 'Optional voice or music track the video is generated to.' }],
    pricing: wan27Pricing,
    featured: true,
    isNew: true,
  },
  {
    id: 'wan-2.7-i2v',
    family: 'wan',
    name: 'Wan 2.7',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'First → last frame animation up to 15s, optionally driven by a voice or music track.',
    tags: ['Start + end frame', '1080p', 'Audio-driven'],
    api: 'market',
    kieModel: 'wan/2-7-image-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [wanRes1080, durationRange(2, 15, 5), negativePrompt(), promptExtend('prompt_extend', true), wanWatermark, seedField()],
    media: [
      frame('start_frame', 'first_frame_url', true),
      frame('end_frame', 'last_frame_url', false, 'Optional — the clip ends on this image.'),
      { key: 'audio', api: 'driving_audio_url', kind: 'audio', label: 'Driving audio', max: 1, single: true, help: 'Optional voice or music the motion follows.' },
    ],
    pricing: wan27Pricing,
    isNew: true,
  },
  {
    id: 'wan-2.7-extend',
    family: 'wan',
    name: 'Wan 2.7 Continue',
    provider: 'Alibaba',
    mode: 'video-to-video',
    bestFor: 'Continuing an existing clip from its last moment with a new prompt, up to 15s more.',
    tags: ['Extend', '1080p'],
    api: 'market',
    kieModel: 'wan/2-7-image-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [wanRes1080, durationRange(2, 15, 5), negativePrompt(), promptExtend('prompt_extend', true), wanWatermark, seedField()],
    media: [{ key: 'video', api: 'first_clip_url', kind: 'video', label: 'Clip to continue', min: 1, max: 1, single: true, help: 'The new footage picks up where this clip ends.' }],
    pricing: wan27Pricing,
    isNew: true,
  },
  {
    id: 'wan-2.6',
    family: 'wan',
    name: 'Wan 2.6',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: 'Up to 15s 1080p story clips with optional automatic multi-shot cutting.',
    tags: ['Multi-shot', '1080p', 'Up to 15s'],
    api: 'market',
    kieModel: 'wan/2-6-text-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [wanRes1080, seconds([5, 10, 15], 5), wan26MultiShots],
    media: [],
    pricing: wan26Pricing,
  },
  {
    id: 'wan-2.6-i2v',
    family: 'wan',
    name: 'Wan 2.6',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Turning one image into a 15s multi-shot sequence at 1080p.',
    tags: ['Multi-shot', '1080p', 'Up to 15s'],
    api: 'market',
    kieModel: 'wan/2-6-image-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [wanRes1080, seconds([5, 10, 15], 5), wan26MultiShots],
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: 'At least 256px, up to 10MB.' }],
    pricing: wan26Pricing,
  },
  {
    id: 'wan-2.6-flash-i2v',
    family: 'wan',
    name: 'Wan 2.6 Flash',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Faster Wan 2.6 image animation that can add generated sound to the clip.',
    tags: ['Fast', 'Native audio', 'Multi-shot'],
    api: 'market',
    kieModel: 'wan/2-6-flash-image-to-video',
    output: 'video',
    audio: true,
    promptMax: 1500,
    fields: [
      wanRes1080,
      seconds([5, 10, 15], 5),
      { key: 'audio', label: 'Native audio', type: 'boolean', default: false, help: 'Generate sound with the video.' },
      wan26MultiShots,
    ],
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1 }],
    // price unverified — Wan 2.6 Flash is not in the pricing feed; using Wan 2.6 I2V rates rounded up
    pricing: { by: ['resolution', 'duration'], table: { '720p|5': 70, '720p|10': 140, '720p|15': 210, '1080p|5': 105, '1080p|10': 210, '1080p|15': 315 } },
  },
  {
    id: 'wan-2.5',
    family: 'wan',
    name: 'Wan 2.5',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: 'Short, prompt-faithful 5–10s clips with negative prompts and seeds for repeatable results.',
    tags: ['1080p', '5s / 10s'],
    api: 'market',
    kieModel: 'wan/2-5-text-to-video',
    output: 'video',
    promptMax: 800,
    fields: [ratio('aspectRatio', ['16:9', '9:16', '1:1'], '16:9'), wanRes1080, seconds([5, 10], 5), negativePrompt(), promptExtend('enable_prompt_expansion', true), seedField()],
    media: [],
    pricing: wan25Pricing,
  },
  {
    id: 'wan-2.5-i2v',
    family: 'wan',
    name: 'Wan 2.5',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Controlled image animation with negative prompts and seeds for repeatable takes.',
    tags: ['1080p', '5s / 10s'],
    api: 'market',
    kieModel: 'wan/2-5-image-to-video',
    output: 'video',
    promptMax: 800,
    fields: [wanRes1080, seconds([5, 10], 5), negativePrompt(), promptExtend('enable_prompt_expansion', true), seedField()],
    media: [frame('start_frame', 'image_url', true)],
    pricing: wan25Pricing,
  },
  {
    id: 'wan-2.2-turbo',
    family: 'wan',
    name: 'Wan 2.2 Turbo',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: 'Cheap 5s drafts at 480p or 720p to iterate on a prompt quickly.',
    tags: ['Budget', 'Fast', '5s'],
    api: 'market',
    kieModel: 'wan/2-2-a14b-text-to-video-turbo',
    output: 'video',
    promptMax: 5000,
    fields: [ratio('aspectRatio', ['16:9', '9:16'], '16:9'), ...wan22Fields],
    media: [],
    pricing: wan22Pricing,
  },
  {
    id: 'wan-2.2-turbo-i2v',
    family: 'wan',
    name: 'Wan 2.2 Turbo',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Cheap 5s image animations for drafts and quick social loops.',
    tags: ['Budget', 'Fast', '5s'],
    api: 'market',
    kieModel: 'wan/2-2-a14b-image-to-video-turbo',
    output: 'video',
    promptMax: 5000,
    fields: wan22Fields,
    media: [frame('start_frame', 'image_url', true, 'Up to 10MB.')],
    pricing: wan22Pricing,
  },

  // ─── Alibaba · HappyHorse ─────────────────────────────────────────────────
  {
    id: 'happyhorse-1.1',
    family: 'happyhorse',
    name: 'HappyHorse 1.1',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: 'Clips up to 15s in 9 aspect ratios (4:5, 21:9…) — cheaper per second than HappyHorse 1.0.',
    tags: ['1080p', 'Up to 15s', '9 ratios'],
    api: 'market',
    kieModel: 'happyhorse-1-1/text-to-video',
    output: 'video',
    promptMax: 4999,
    fields: [
      ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4', '4:5', '5:4', '9:21', '21:9'], '16:9'),
      wanRes1080,
      durationRange(3, 15, 5),
    ],
    media: [],
    pricing: hhPricing11,
    isNew: true,
  },
  {
    id: 'happyhorse-1.1-i2v',
    family: 'happyhorse',
    name: 'HappyHorse 1.1',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Animating a single image for up to 15s at 1080p, prompt optional.',
    tags: ['1080p', 'Up to 15s'],
    api: 'market',
    kieModel: 'happyhorse-1-1/image-to-video',
    output: 'video',
    promptRequired: false,
    promptMax: 5000,
    fields: [wanRes1080, durationRange(3, 15, 5)],
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: 'Up to 20MB.' }],
    pricing: hhPricing11,
    isNew: true,
  },
  {
    id: 'happyhorse-1.0',
    family: 'happyhorse',
    name: 'HappyHorse 1.0',
    provider: 'Alibaba',
    mode: 'text-to-video',
    bestFor: 'Seeded, repeatable 3–15s clips at 1080p when you need to reproduce a take.',
    tags: ['1080p', 'Up to 15s', 'Seed'],
    api: 'market',
    kieModel: 'happyhorse/text-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4'], '16:9'), wanRes1080, durationRange(3, 15, 5), seedField()],
    media: [],
    pricing: hhPricing10,
  },
  {
    id: 'happyhorse-1.0-i2v',
    family: 'happyhorse',
    name: 'HappyHorse 1.0',
    provider: 'Alibaba',
    mode: 'image-to-video',
    bestFor: 'Seeded image animation up to 15s at 1080p, prompt optional.',
    tags: ['1080p', 'Up to 15s', 'Seed'],
    api: 'market',
    kieModel: 'happyhorse/image-to-video',
    output: 'video',
    promptRequired: false,
    promptMax: 5000,
    fields: [wanRes1080, durationRange(3, 15, 5), seedField()],
    // Doc schema key is 'image_urls ' (trailing space); the example uses 'image_urls'.
    media: [{ key: 'start_frame', api: 'image_urls', kind: 'image', label: 'Start frame', min: 1, max: 1, help: '≥300px, aspect 1:2.5–2.5:1, up to 10MB.' }],
    pricing: hhPricing10,
  },

  // ─── xAI · Grok Imagine ───────────────────────────────────────────────────
  {
    id: 'grok-imagine',
    family: 'grok',
    name: 'Grok Imagine',
    provider: 'xAI',
    mode: 'text-to-video',
    bestFor: 'Fast, playful social clips and memes — the cheapest per-second way to try a video idea.',
    tags: ['Fast', 'Budget', 'Up to 30s'],
    api: 'market',
    kieModel: 'grok-imagine/text-to-video',
    output: 'video',
    promptMax: 5000,
    fields: [
      grokRatio('2:3'),
      {
        key: 'mode', label: 'Motion style', type: 'enum', default: 'normal',
        options: [{ value: 'normal', label: 'Normal' }, { value: 'fun', label: 'Fun' }, { value: 'spicy', label: 'Spicy' }],
      },
      durationRange(6, 30, 6, 'string'),
      grokResolution,
    ],
    media: [],
    pricing: grokPricing,
  },
  {
    id: 'grok-imagine-i2v',
    family: 'grok',
    name: 'Grok Imagine',
    provider: 'xAI',
    mode: 'image-to-video',
    bestFor: 'Quick, lively animations of photos or memes; combine up to 7 images in one clip.',
    tags: ['Fast', 'Budget', 'Multi-image'],
    api: 'market',
    kieModel: 'grok-imagine/image-to-video',
    output: 'video',
    promptRequired: false,
    promptMax: 5000,
    fields: [
      { ...grokRatio('16:9'), help: 'Only used when you add 2 or more images.' },
      {
        key: 'mode', label: 'Motion style', type: 'enum', default: 'normal',
        options: [{ value: 'normal', label: 'Normal' }, { value: 'fun', label: 'Fun' }],
        help: 'Spicy is not available with uploaded images.',
      },
      durationRange(6, 30, 6, 'string'),
      grokResolution,
    ],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images', min: 1, max: 7, help: 'JPG/PNG/WebP up to 10MB. Refer to them as @image1, @image2… in the prompt.' }],
    pricing: grokPricing,
  },

  // ─── PixVerse V6 ──────────────────────────────────────────────────────────
  {
    id: 'pixverse-v6',
    family: 'pixverse',
    name: 'PixVerse V6',
    provider: 'PixVerse',
    mode: 'text-to-video',
    bestFor: 'Low-cost stylized social clips with optional sound, from 360p drafts to 1080p finals.',
    tags: ['Native audio', 'Budget', '1080p'],
    api: 'market',
    kieModel: 'pixverse-v6/text-to-video',
    output: 'video',
    audio: true,
    promptMax: 5000,
    fields: [ratio('aspectRatio', ['16:9', '9:16', '1:1', '4:3', '3:4', '3:2', '2:3', '21:9'], '16:9'), ...pixverseFields, pixverseMultiClip],
    media: [],
    pricing: pixversePricing,
    isNew: true,
  },
  {
    id: 'pixverse-v6-i2v',
    family: 'pixverse',
    name: 'PixVerse V6',
    provider: 'PixVerse',
    mode: 'image-to-video',
    bestFor: 'Cheap image animation with optional generated sound, great for social loops.',
    tags: ['Native audio', 'Budget', '1080p'],
    api: 'market',
    kieModel: 'pixverse-v6/image-to-video',
    output: 'video',
    audio: true,
    promptMax: 5000,
    fields: [...pixverseFields, pixverseMultiClip],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images', min: 1, max: 2, help: 'Up to 2 images, 20MB each.' }],
    pricing: pixversePricing,
    isNew: true,
  },
  {
    id: 'pixverse-v6-transition',
    family: 'pixverse',
    name: 'PixVerse V6 Transition',
    provider: 'PixVerse',
    mode: 'image-to-video',
    bestFor: 'Morphing one image into another — before/after reveals and scene transitions.',
    tags: ['Start + end frame', 'Transition', 'Native audio'],
    api: 'market',
    kieModel: 'pixverse-v6/transition',
    output: 'video',
    audio: true,
    promptMax: 5000,
    fields: pixverseFields,
    media: [
      frame('start_frame', 'first_frame_image_url', true, 'Up to 20MB.'),
      frame('end_frame', 'last_frame_image_url', true, 'Up to 20MB. The clip ends on this image.'),
    ],
    // price unverified — transition has no separate feed rows; using PixVerse V6 text/image-to-video rates
    pricing: pixversePricing,
    isNew: true,
  },
];
