// Image edit / image-to-image models on kie.ai (plus upscale, background
// removal, layer decomposition and character references).
// Control keys for pre-catalog models are kept as they were so saved
// generations and presets still regenerate correctly.

import type { FieldSpec, ModelSpec } from './types.ts';
import { negativePrompt, opts, ratio, seedField } from './helpers.ts';
import { RATIOS_FLUX, RATIOS_NB, RATIOS_WIDE, fluxResolution, nbFormat, nbResolution, seedreamQuality } from './models-image.ts';

// ─── Local enums / shared fields ─────────────────────────────────────────────
// Flux 2 image-to-image: the T2I ratios plus 3:2 / 2:3 and `auto`.
const RATIOS_FLUX2_I2I = ['auto', ...RATIOS_FLUX, '3:2', '2:3'];
const RATIOS_NB2 = ['auto', '1:1', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '9:16', '16:9', '21:9', '1:4', '4:1', '1:8', '8:1'];
const RATIOS_NB_EDIT = ['1:1', '9:16', '16:9', '3:4', '4:3', '3:2', '2:3', '5:4', '4:5', '21:9', 'auto'];
const RATIOS_GPT2 = ['auto', '1:1', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5', '16:9', '9:16', '2:1', '1:2', '3:1', '1:3', '21:9', '9:21'];
const RATIOS_GPT25 = ['auto', '1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9', '27:16', '16:27', '9:8', '8:9'];
const RATIOS_KONTEXT = ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'];
const RATIOS_QWEN21 = ['auto', '1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', '9:21'];
const RATIOS_QWEN3 = ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'];

const FAL_SIZES = [
  { value: 'square_hd', label: 'Square HD' }, { value: 'square', label: 'Square' },
  { value: 'portrait_4_3', label: 'Portrait 3:4' }, { value: 'portrait_16_9', label: 'Portrait 9:16' },
  { value: 'landscape_4_3', label: 'Landscape 4:3' }, { value: 'landscape_16_9', label: 'Landscape 16:9' },
];

const nsfwChecker = (def: boolean): FieldSpec => ({ key: 'nsfw_checker', label: 'Safety checker', type: 'boolean', default: def, advanced: true });
const outputFormat = (values: string[], def: string): FieldSpec => ({
  key: 'output_format', label: 'Format', type: 'enum', options: values.map((v) => ({ value: v, label: v.toUpperCase() })), default: def, advanced: true,
});
const gptResolution: FieldSpec = {
  key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K', '4K'), default: '1K',
  help: 'Auto aspect ratio only renders at 1K; some ratios are 1K/2K only.',
};
const gptBackground = (when?: FieldSpec['when']): FieldSpec => ({
  key: 'background', label: 'Background', type: 'enum', default: 'auto', when,
  options: [{ value: 'auto', label: 'Auto' }, { value: 'opaque', label: 'Opaque' }, { value: 'transparent', label: 'Transparent' }],
});

// Ideogram
const ideogramSpeed: FieldSpec = {
  key: 'rendering_speed', label: 'Speed', type: 'enum', default: 'BALANCED',
  options: [{ value: 'TURBO', label: 'Turbo' }, { value: 'BALANCED', label: 'Balanced' }, { value: 'QUALITY', label: 'Quality' }],
};
const ideogramExpand: FieldSpec = {
  key: 'expand_prompt', label: 'Magic prompt', type: 'boolean', default: true, advanced: true, help: 'Let Ideogram expand your prompt before rendering.',
};
const ideogramStyleV3: FieldSpec = {
  key: 'style', label: 'Style', type: 'enum', default: 'AUTO',
  options: [{ value: 'AUTO', label: 'Auto' }, { value: 'GENERAL', label: 'General' }, { value: 'REALISTIC', label: 'Realistic' }, { value: 'DESIGN', label: 'Design' }],
};
const ideogramStyleCharacter: FieldSpec = {
  key: 'style', label: 'Style', type: 'enum', default: 'AUTO',
  options: [{ value: 'AUTO', label: 'Auto' }, { value: 'REALISTIC', label: 'Realistic' }, { value: 'FICTION', label: 'Fiction' }],
};
const ideogramSize: FieldSpec = { key: 'image_size', label: 'Output size', type: 'enum', options: FAL_SIZES, default: 'square_hd' };
const IDEOGRAM_V3_PRICE = { by: 'rendering_speed', table: { TURBO: 3.5, BALANCED: 7, QUALITY: 10 } };
const IDEOGRAM_CHARACTER_PRICE = { by: 'rendering_speed', table: { TURBO: 12, BALANCED: 18, QUALITY: 24 } };
const characterSlot = { key: 'character', api: 'reference_image_urls', kind: 'image' as const, label: 'Character reference', min: 1, max: 1, help: 'One clear photo of the character (only the first image is used).' };

// Qwen 3
const qwen3Fields: FieldSpec[] = [
  { key: 'image_size', label: 'Aspect ratio', type: 'enum', options: opts(...RATIOS_QWEN3), default: '16:9' },
  { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K'), default: '1K' },
  outputFormat(['png', 'jpeg'], 'png'),
  { key: 'prompt_extend', label: 'Prompt extend', type: 'boolean', default: true, advanced: true, help: 'Let the model rewrite and enrich your prompt.' },
  negativePrompt(),
  seedField(),
  nsfwChecker(false),
];

// Wan 2.7 image (edit mode: aspect ratio / thinking mode only apply without input images)
const wanImageFields = (resolutions: string[]): FieldSpec[] => [
  { key: 'resolution', label: 'Resolution', type: 'enum', options: opts(...resolutions), default: '2K' },
  { key: 'watermark', label: 'Watermark', type: 'boolean', default: false, advanced: true },
  seedField(),
];

export const IMAGE_EDIT_SPECS: ModelSpec[] = [
  // ─── Google ────────────────────────────────────────────────────────────────
  {
    id: 'nano-banana-pro-i2i',
    family: 'nano-banana',
    name: 'Nano Banana Pro Edit',
    provider: 'Google',
    mode: 'image-to-image',
    bestFor: 'Faithful edits and multi-image composites that keep faces, products and text intact.',
    tags: ['Identity lock', 'Multi-image', '4K'],
    api: 'market',
    kieModel: 'nano-banana-pro',
    output: 'image',
    promptMax: 10000,
    fields: [ratio('aspect_ratio', RATIOS_NB, 'auto'), nbResolution, nbFormat],
    media: [{ key: 'images', api: 'image_input', kind: 'image', label: 'Images to edit', min: 1, max: 8, help: 'Up to 8 (≤30MB each). Refer to them as Image 1, Image 2… in the prompt.' }],
    pricing: { by: 'resolution', table: { '1K': 18, '2K': 18, '4K': 24 } },
    featured: true,
  },
  {
    id: 'nano-banana-2-edit',
    family: 'nano-banana',
    name: 'Nano Banana 2 Edit',
    provider: 'Google',
    mode: 'image-to-image',
    bestFor: 'Blending up to 14 references into one scene at half the price of Nano Banana Pro.',
    tags: ['14 references', '4K', 'Value'],
    api: 'market',
    kieModel: 'nano-banana-2',
    output: 'image',
    promptMax: 20000,
    fields: [
      ratio('aspect_ratio', RATIOS_NB2, 'auto'),
      nbResolution,
      outputFormat(['png', 'jpg'], 'jpg'),
    ],
    media: [{ key: 'images', api: 'image_input', kind: 'image', label: 'Images to edit', min: 1, max: 14, help: 'Up to 14 (≤30MB each). Refer to them as Image 1, Image 2… in the prompt.' }],
    pricing: { by: 'resolution', table: { '1K': 8, '2K': 12, '4K': 18 } },
    featured: true,
    isNew: true,
  },
  {
    id: 'nano-banana-2-lite-edit',
    family: 'nano-banana',
    name: 'Nano Banana 2 Lite Edit',
    provider: 'Google',
    mode: 'image-to-image',
    bestFor: 'Quick, low-cost 1K edits and variations when you need many tries.',
    tags: ['Budget', 'Fast', 'Multi-image'],
    api: 'market',
    kieModel: 'nano-banana-2-lite',
    output: 'image',
    promptMax: 20000,
    fields: [ratio('aspect_ratio', RATIOS_NB2, 'auto')],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 10, help: 'Up to 10 (≤30MB each).' }],
    pricing: { credits: 4 },
    isNew: true,
  },
  {
    id: 'nano-banana-edit',
    family: 'nano-banana',
    name: 'Nano Banana Edit',
    provider: 'Google',
    mode: 'image-to-image',
    bestFor: 'Cheap, playful photo edits like figurines, outfit swaps and scene changes.',
    tags: ['Budget', 'Multi-image'],
    api: 'market',
    kieModel: 'google/nano-banana-edit',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_NB_EDIT, '1:1'), outputFormat(['png', 'jpeg'], 'png')],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 10, help: 'Up to 10 (≤10MB each).' }],
    pricing: { credits: 4 },
  },

  // ─── OpenAI ────────────────────────────────────────────────────────────────
  {
    id: 'gpt-image-2-edit',
    family: 'gpt',
    name: 'GPT Image 2 Edit',
    provider: 'OpenAI',
    mode: 'image-to-image',
    bestFor: 'Instruction-heavy edits that follow long briefs exactly, including text and layout changes.',
    tags: ['Instruction following', '16 references', '4K'],
    api: 'market',
    kieModel: 'gpt-image-2-image-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [ratio('aspect_ratio', RATIOS_GPT2, 'auto'), gptResolution, gptBackground({ key: 'resolution', in: ['1K'] })],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 16, help: 'Up to 16 images.' }],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    featured: true,
    isNew: true,
  },
  {
    id: 'gpt-image-2.5-flare-edit',
    family: 'gpt',
    name: 'GPT Image 2.5 Flare Edit',
    provider: 'OpenAI',
    mode: 'image-to-image',
    bestFor: 'Turning product photos into polished ads and posters, with transparent backgrounds at any size.',
    tags: ['Transparent BG', '4K', '16 references'],
    api: 'market',
    kieModel: 'gpt-image-2-5-flare-image-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [ratio('aspect_ratio', RATIOS_GPT25, 'auto'), gptResolution, gptBackground()],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 16, help: 'Up to 16 images.' }],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    isNew: true,
  },
  {
    id: 'gpt-image-2.5-sunburst-edit',
    family: 'gpt',
    name: 'GPT Image 2.5 Sunburst Edit',
    provider: 'OpenAI',
    mode: 'image-to-image',
    bestFor: 'An alternate GPT Image 2.5 look for the same edits; compare it with Flare on key shots.',
    tags: ['Transparent BG', '4K', '16 references'],
    api: 'market',
    kieModel: 'gpt-image-2-5-sunburst-image-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [ratio('aspect_ratio', RATIOS_GPT25, 'auto'), gptResolution, gptBackground()],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 16, help: 'Up to 16 images.' }],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    isNew: true,
  },
  {
    id: 'gpt-image-1.5-edit',
    family: 'gpt',
    name: 'GPT Image 1.5 Edit',
    provider: 'OpenAI',
    mode: 'image-to-image',
    bestFor: 'Virtual try-ons and garment swaps that keep the person’s likeness, cheap at medium quality.',
    tags: ['Try-on', '16 references'],
    api: 'market',
    kieModel: 'gpt-image/1.5-image-to-image',
    output: 'image',
    fields: [
      ratio('aspect_ratio', ['1:1', '2:3', '3:2'], '3:2'),
      { key: 'quality', label: 'Quality', type: 'enum', options: [{ value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }], default: 'medium' },
    ],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 16, help: 'Up to 16 (≤10MB each).' }],
    pricing: { by: 'quality', table: { medium: 4, high: 22 } },
  },
  {
    id: 'gpt-4o-edit',
    family: 'gpt',
    name: 'GPT-4o Image Edit',
    provider: 'OpenAI',
    mode: 'image-to-image',
    bestFor: 'Conversational edits of up to 5 photos using the classic GPT-4o image model.',
    tags: ['Instruction following'],
    api: 'gpt4o',
    output: 'image',
    fields: [{ key: 'size', label: 'Aspect ratio', type: 'enum', options: opts('1:1', '3:2', '2:3'), default: '1:1' }],
    media: [{ key: 'images', api: 'filesUrl', kind: 'image', label: 'Images to edit', min: 1, max: 5, help: 'Up to 5 (jpg, png, webp).' }],
    pricing: { credits: 6 },
  },

  // ─── ByteDance Seedream ────────────────────────────────────────────────────
  {
    id: 'seedream-5-pro-edit',
    family: 'seedream',
    name: 'Seedream 5 Pro Edit',
    provider: 'ByteDance',
    mode: 'image-to-image',
    bestFor: 'Material and lighting changes that keep pose and composition, from up to 10 references.',
    tags: ['Multi-reference', 'Detail'],
    api: 'market',
    kieModel: 'seedream/5-pro-image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', RATIOS_WIDE),
      { key: 'quality', label: 'Quality', type: 'enum', options: [{ value: 'basic', label: '1K' }, { value: 'high', label: '2K' }], default: 'basic' },
      outputFormat(['png', 'jpeg'], 'png'),
      nsfwChecker(true),
    ],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 10, help: 'Up to 10. Each image after the first adds 0.5 credits.' }],
    // Extra input images (0.5 each, first free) are not included in this estimate.
    pricing: { by: 'quality', table: { basic: 7, high: 14 } },
    isNew: true,
  },
  {
    id: 'seedream-5-lite-edit',
    family: 'seedream',
    name: 'Seedream 5 Lite Edit',
    provider: 'ByteDance',
    mode: 'image-to-image',
    bestFor: 'Budget restyles up to 4K that blend as many as 14 reference images.',
    tags: ['4K', '14 references', 'Budget'],
    api: 'market',
    kieModel: 'seedream/5-lite-image-to-image',
    output: 'image',
    promptMax: 3000,
    fields: [
      ratio('aspect_ratio', RATIOS_WIDE),
      {
        key: 'quality', label: 'Quality', type: 'enum', default: 'basic',
        options: [{ value: 'basic', label: '2K' }, { value: 'high', label: '3K' }, { value: 'ultra', label: '4K' }],
      },
      outputFormat(['png', 'jpeg'], 'png'),
      nsfwChecker(true),
    ],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 14, help: 'Up to 14 images.' }],
    pricing: { credits: 5.5 },
    isNew: true,
  },
  {
    id: 'seedream-4.5-edit',
    family: 'seedream',
    name: 'Seedream 4.5 Edit',
    provider: 'ByteDance',
    mode: 'image-to-image',
    bestFor: 'Style transfer and aesthetic restyles of one or several images, cheaply.',
    tags: ['Style transfer', 'Budget'],
    api: 'market',
    kieModel: 'seedream/4.5-edit',
    output: 'image',
    promptMax: 3000,
    fields: [ratio('aspect_ratio', RATIOS_WIDE), seedreamQuality, nsfwChecker(true)],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 14, help: 'Up to 14 (≤30MB each).' }],
    pricing: { credits: 6.5 },
  },
  {
    id: 'seedream-4-edit',
    family: 'seedream',
    name: 'Seedream 4.0 Edit',
    provider: 'ByteDance',
    mode: 'image-to-image',
    bestFor: 'Brand mockups from a logo or product shot, with a seed for repeatable results.',
    tags: ['Mockups', '4K', 'Seed'],
    api: 'market',
    kieModel: 'bytedance/seedream-v4-edit',
    output: 'image',
    promptMax: 5000,
    fields: [
      {
        key: 'image_size', label: 'Output size', type: 'enum', default: 'square_hd',
        options: [
          ...FAL_SIZES,
          { value: 'portrait_3_2', label: 'Portrait 2:3' }, { value: 'landscape_3_2', label: 'Landscape 3:2' },
          { value: 'landscape_21_9', label: 'Landscape 21:9' },
        ],
      },
      { key: 'image_resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K', '4K'), default: '1K' },
      seedField(),
      nsfwChecker(true),
    ],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 10, help: 'Up to 10 (jpeg/png/webp, ≤30MB each).' }],
    // price unverified — Seedream 4.0 is not in the pricing feed; Seedream 4.5 Edit (6.5) rounded up.
    pricing: { credits: 7 },
  },
  {
    id: 'seedream-5-pro-layers',
    family: 'seedream',
    name: 'Seedream 5 Pro Layers',
    provider: 'ByteDance',
    mode: 'image-to-image',
    bestFor: 'Splitting a flat image into separate transparent PNG layers for editing in design tools.',
    tags: ['Layers', 'PNG'],
    api: 'market',
    kieModel: 'seedream/5-pro-layer-decomposition',
    output: 'image',
    promptRequired: false,
    promptMax: 5000,
    fields: [
      {
        key: 'size', label: 'Size', type: 'enum', default: 'auto',
        options: [{ value: 'auto', label: 'Auto' }, { value: '1K', label: '1K' }, { value: '1.5K', label: '1.5K' }, { value: '2K', label: '2K' }],
      },
      { ...outputFormat(['jpeg', 'png'], 'jpeg'), label: 'Base image format', help: 'Applies to the base image only; layers are always PNG.' },
    ],
    media: [{
      key: 'images', api: 'image_url', kind: 'image', label: 'Image to split', min: 1, max: 1, single: true,
      help: 'One image, ≤30MB, no HEIC. Optional prompt can target a region with <bbox>x1 y1 x2 y2</bbox>.',
    }],
    // price unverified — `auto` size is not in the pricing feed; charged at the 2K price (14).
    pricing: { by: 'size', table: { auto: 14, '1K': 7, '1.5K': 7, '2K': 14 } },
    isNew: true,
  },

  // ─── Black Forest Labs ─────────────────────────────────────────────────────
  {
    id: 'flux-kontext-edit',
    family: 'flux-kontext',
    name: 'Flux Kontext Edit',
    provider: 'Black Forest Labs',
    mode: 'image-to-image',
    bestFor: 'Targeted local edits to one image (swap an object, change text) while the rest stays untouched.',
    tags: ['Local edits', 'Pro / Max'],
    api: 'kontext',
    output: 'image',
    fields: [
      {
        key: 'kontextModel', api: 'model', label: 'Tier', type: 'enum', default: 'flux-kontext-pro',
        options: [{ value: 'flux-kontext-pro', label: 'Pro' }, { value: 'flux-kontext-max', label: 'Max' }],
        help: 'Max follows complex edits more closely; Pro is half the price.',
      },
      ratio('aspectRatio', RATIOS_KONTEXT, '16:9', 'aspectRatio'),
      { key: 'outputFormat', label: 'Format', type: 'enum', options: [{ value: 'jpeg', label: 'JPEG' }, { value: 'png', label: 'PNG' }], default: 'jpeg', advanced: true },
      { key: 'enableTranslation', label: 'Auto-translate prompt', type: 'boolean', default: true, advanced: true, help: 'Kontext only understands English; this translates other languages.' },
      { key: 'promptUpsampling', label: 'Prompt upsampling', type: 'boolean', default: false, advanced: true },
      { key: 'safetyTolerance', label: 'Safety tolerance', type: 'number', min: 0, max: 2, step: 1, default: 2, advanced: true, help: '0 = strictest, 2 = most permissive (edit mode).' },
      { key: 'watermark', label: 'Watermark', type: 'text', default: '', advanced: true, omitIf: '' },
    ],
    media: [{ key: 'images', api: 'inputImage', kind: 'image', label: 'Image to edit', min: 1, max: 1, single: true }],
    pricing: { by: 'kontextModel', table: { 'flux-kontext-pro': 5, 'flux-kontext-max': 10 } },
  },
  {
    id: 'flux-pro-i2i',
    family: 'flux',
    name: 'Flux 2 Pro Edit',
    provider: 'Black Forest Labs',
    mode: 'image-to-image',
    bestFor: 'Precise, high-detail transformations guided by up to 8 reference images.',
    tags: ['Multi-reference', 'Detail'],
    api: 'market',
    kieModel: 'flux-2/pro-image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_FLUX2_I2I), fluxResolution, nsfwChecker(false)],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Reference images', min: 1, max: 8, help: 'Up to 8 (≤10MB each). Refer to them as image 1, image 2… in the prompt.' }],
    pricing: { by: 'resolution', table: { '1K': 5, '2K': 7 } },
  },
  {
    id: 'flux-flex-i2i',
    family: 'flux',
    name: 'Flux 2 Flex Edit',
    provider: 'Black Forest Labs',
    mode: 'image-to-image',
    bestFor: 'Artistic reinterpretations and stylized remixes of your reference images.',
    tags: ['Stylized', 'Multi-reference'],
    api: 'market',
    kieModel: 'flux-2/flex-image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_FLUX2_I2I), fluxResolution, nsfwChecker(false)],
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Reference images', min: 1, max: 8, help: 'Up to 8 (≤10MB each). Refer to them as image 1, image 2… in the prompt.' }],
    pricing: { by: 'resolution', table: { '1K': 14, '2K': 24 } },
  },

  // ─── xAI ───────────────────────────────────────────────────────────────────
  {
    id: 'grok-imagine-image-2-edit',
    family: 'grok',
    name: 'Grok Imagine Image 2.0 Edit',
    provider: 'xAI',
    mode: 'image-to-image',
    bestFor: 'Poster-style recreations and parodies that restage a reference with new subjects.',
    tags: ['Remix', 'Multi-image'],
    api: 'market',
    kieModel: 'grok-imagine-image-2-0/image-edit',
    output: 'image',
    promptMax: 8000,
    fields: [ratio('aspect_ratio', ['auto', '1:1', '2:3', '3:2', '16:9', '9:16'], 'auto')],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 5, help: 'Up to 5 images.' }],
    pricing: { credits: 4 },
    isNew: true,
  },
  {
    id: 'grok-imagine-image-edit',
    family: 'grok',
    name: 'Grok Imagine Edit',
    provider: 'xAI',
    mode: 'image-to-image',
    bestFor: 'Fast, loose reimaginings of a single image; returns several takes per run.',
    tags: ['Variations', 'Budget'],
    api: 'market',
    kieModel: 'grok-imagine/image-to-image',
    output: 'image',
    promptMax: 390000,
    fields: [],
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Image to edit', min: 1, max: 1, help: '1 image (≤10MB). Refer to it as @image1 in the prompt.' }],
    pricing: { credits: 4 },
  },

  // ─── Ideogram ──────────────────────────────────────────────────────────────
  {
    id: 'ideogram-character',
    family: 'ideogram',
    name: 'Ideogram Character',
    provider: 'Ideogram',
    mode: 'image-to-image',
    bestFor: 'Putting the same person from one photo into new scenes, outfits and poses.',
    tags: ['Character consistency', 'Seed'],
    api: 'market',
    kieModel: 'ideogram/character',
    output: 'image',
    promptMax: 5000,
    fields: [ideogramSpeed, ideogramStyleCharacter, ideogramSize, ideogramExpand, negativePrompt(), seedField()],
    media: [characterSlot],
    pricing: IDEOGRAM_CHARACTER_PRICE,
  },
  {
    id: 'ideogram-character-edit',
    family: 'ideogram',
    name: 'Ideogram Character Edit',
    provider: 'Ideogram',
    mode: 'image-to-image',
    bestFor: 'Repainting a masked area of a photo with a consistent character from a reference.',
    tags: ['Inpaint', 'Character consistency'],
    api: 'market',
    kieModel: 'ideogram/character-edit',
    output: 'image',
    promptMax: 5000,
    fields: [ideogramSpeed, ideogramStyleCharacter, ideogramExpand, seedField()],
    media: [
      { key: 'images', api: 'image_url', kind: 'image', label: 'Image to edit', min: 1, max: 1, single: true },
      { key: 'mask', api: 'mask_url', kind: 'image', label: 'Mask', min: 1, max: 1, single: true, help: 'Same dimensions as the image; marks the area to repaint.' },
      characterSlot,
    ],
    pricing: IDEOGRAM_CHARACTER_PRICE,
  },
  {
    id: 'ideogram-character-remix',
    family: 'ideogram',
    name: 'Ideogram Character Remix',
    provider: 'Ideogram',
    mode: 'image-to-image',
    bestFor: 'Remixing an existing image so it stars your character, with adjustable strength.',
    tags: ['Remix', 'Character consistency'],
    api: 'market',
    kieModel: 'ideogram/character-remix',
    output: 'image',
    promptMax: 5000,
    fields: [
      ideogramSpeed, ideogramStyleCharacter, ideogramSize,
      { key: 'strength', label: 'Remix strength', type: 'number', min: 0.1, max: 1, step: 0.05, default: 0.8, help: 'Higher = further from the source image.' },
      ideogramExpand,
      { ...negativePrompt(), help: 'Things to keep out of the result (max 500 chars).' },
      seedField(),
    ],
    media: [
      { key: 'images', api: 'image_url', kind: 'image', label: 'Image to remix', min: 1, max: 1, single: true },
      characterSlot,
      { key: 'ref_images', api: 'image_urls', kind: 'image', label: 'Style references', max: 4, help: 'Optional images whose style to borrow.' },
      { key: 'mask', api: 'reference_mask_urls', kind: 'image', label: 'Character mask', max: 1, single: true, help: 'Optional mask isolating the character in the reference photo.' },
    ],
    pricing: IDEOGRAM_CHARACTER_PRICE,
  },
  {
    id: 'ideogram-v3-edit',
    family: 'ideogram',
    name: 'Ideogram V3 Edit',
    provider: 'Ideogram',
    mode: 'image-to-image',
    bestFor: 'Mask-based inpainting — add or replace an object in one exact area of an image.',
    tags: ['Inpaint', 'Mask'],
    api: 'market',
    kieModel: 'ideogram/v3-edit',
    output: 'image',
    promptMax: 5000,
    fields: [ideogramSpeed, ideogramExpand, seedField()],
    media: [
      { key: 'images', api: 'image_url', kind: 'image', label: 'Image to edit', min: 1, max: 1, single: true, help: '≤10MB.' },
      { key: 'mask', api: 'mask_url', kind: 'image', label: 'Mask', min: 1, max: 1, single: true, help: 'Same dimensions as the image; marks the area to repaint.' },
    ],
    pricing: IDEOGRAM_V3_PRICE,
  },
  {
    id: 'ideogram-v3-remix',
    family: 'ideogram',
    name: 'Ideogram V3 Remix',
    provider: 'Ideogram',
    mode: 'image-to-image',
    bestFor: 'Reworking a graphic or design into a new version while keeping its overall layout.',
    tags: ['Remix', 'Design'],
    api: 'market',
    kieModel: 'ideogram/v3-remix',
    output: 'image',
    promptMax: 5000,
    fields: [
      ideogramSpeed, ideogramStyleV3, ideogramSize,
      { key: 'strength', label: 'Remix strength', type: 'number', min: 0.01, max: 1, step: 0.01, default: 0.8, help: 'Higher = further from the source image.' },
      ideogramExpand,
      negativePrompt(),
      seedField(),
    ],
    media: [{ key: 'images', api: 'image_url', kind: 'image', label: 'Image to remix', min: 1, max: 1, single: true }],
    pricing: IDEOGRAM_V3_PRICE,
  },

  // ─── Alibaba Qwen ──────────────────────────────────────────────────────────
  {
    id: 'qwen-3-pro-edit',
    family: 'qwen',
    name: 'Qwen Image 3 Pro Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Higher-fidelity restyles of up to 3 images at 2K, when Qwen 3 standard lacks detail.',
    tags: ['2K', 'Restyle'],
    api: 'market',
    kieModel: 'qwen3/pro-image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: qwen3Fields,
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 3, help: 'Up to 3 (≤10MB each).' }],
    // Input images add 0.5 credits each; not included in this estimate.
    pricing: { by: 'resolution', table: { '1K': 6.4, '2K': 12 } },
    isNew: true,
  },
  {
    id: 'qwen-3-edit',
    family: 'qwen',
    name: 'Qwen Image 3 Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Low-cost restyles such as photo to watercolor, with the same price at 1K and 2K.',
    tags: ['Budget', 'Restyle'],
    api: 'market',
    kieModel: 'qwen3/image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: qwen3Fields,
    media: [{ key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 3, help: 'Up to 3 (≤10MB each).' }],
    // Input images add 0.5 credits each; not included in this estimate.
    pricing: { credits: 4.8 },
    isNew: true,
  },
  {
    id: 'qwen-2.1-edit',
    family: 'qwen',
    name: 'Qwen Image 2.1 Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Recoloring or swapping parts across up to 10 images, with optional mask inpainting and transparency.',
    tags: ['Mask', 'Transparent BG', 'Multi-image'],
    api: 'market',
    kieModel: 'qwen2-1/image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', RATIOS_QWEN21, 'auto'),
      { key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K'), default: '1K' },
      {
        key: 'background', label: 'Background', type: 'enum', default: 'opaque',
        options: [{ value: 'opaque', label: 'Opaque' }, { value: 'transparent', label: 'Transparent' }],
        help: 'Transparent needs PNG or WEBP output.',
      },
      outputFormat(['png', 'webp', 'jpeg'], 'png'),
      { key: 'enhance_prompt', label: 'Enhance prompt', type: 'boolean', default: true, advanced: true },
      seedField(),
    ],
    media: [
      { key: 'images', api: 'image_urls', kind: 'image', label: 'Images to edit', min: 1, max: 10, help: 'Up to 10 (≤30MB, ≤25MP each). Refer to them as the first image, second image…' },
      { key: 'mask', api: 'mask_url', kind: 'image', label: 'Mask (optional)', max: 1, single: true, help: 'Inpaint only the white area. Requires exactly 1 image.' },
    ],
    pricing: { by: 'resolution', table: { '1K': 4, '2K': 8 } },
  },
  {
    id: 'qwen-2-edit',
    family: 'qwen',
    name: 'Qwen Image 2 Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Short, direct single-image edits with a fixed aspect ratio of your choice.',
    tags: ['Simple edits'],
    api: 'market',
    kieModel: 'qwen2/image-edit',
    output: 'image',
    promptMax: 800,
    fields: [
      { key: 'image_size', label: 'Aspect ratio', type: 'enum', options: opts('1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'), default: '16:9' },
      outputFormat(['png', 'jpeg'], 'png'),
      seedField(),
    ],
    media: [{ key: 'images', api: 'image_url', kind: 'image', label: 'Image to edit', min: 1, max: 1, single: true }],
    pricing: { credits: 5.6 },
  },
  {
    id: 'qwen-image-edit',
    family: 'qwen',
    name: 'Qwen Image Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Surgical one-line edits — remove objects, swap colors, rewrite text on signs.',
    tags: ['Text edits', 'Budget'],
    api: 'market',
    kieModel: 'qwen/image-edit',
    output: 'image',
    promptMax: 2000,
    fields: [
      { key: 'image_size', label: 'Output size', type: 'enum', default: 'landscape_4_3', options: FAL_SIZES },
      { key: 'guidance_scale', label: 'Guidance', type: 'number', min: 0, max: 20, step: 0.5, default: 4, advanced: true, help: 'How strictly to follow the prompt.' },
      { key: 'num_inference_steps', label: 'Steps', type: 'number', min: 2, max: 49, default: 25, advanced: true },
      { key: 'negative_prompt', label: 'Negative prompt', type: 'text', default: 'blurry, ugly', advanced: true },
      { key: 'seed', label: 'Seed', type: 'seed', advanced: true },
      { key: 'acceleration', label: 'Acceleration', type: 'enum', options: opts('none', 'regular', 'high'), default: 'none', advanced: true },
      { key: 'output_format', label: 'Format', type: 'enum', options: opts('png', 'jpeg'), default: 'png', advanced: true },
      { key: 'enable_safety_checker', label: 'Safety checker', type: 'boolean', default: true, advanced: true },
    ],
    media: [{ key: 'images', api: 'image_url', kind: 'image', label: 'Image to edit', min: 1, max: 1, single: true }],
    fixed: { sync_mode: false },
    // price unverified — feed bills 5 credits per megapixel; assumes the standard
    // fal-style sizes (square_hd 1024², *_4_3 1024×768, *_16_9 1024×576, square 512²), rounded up.
    pricing: {
      by: 'image_size',
      table: { square_hd: 6, square: 2, portrait_4_3: 4, landscape_4_3: 4, portrait_16_9: 3, landscape_16_9: 3 },
    },
  },
  {
    id: 'qwen-image-remix',
    family: 'qwen',
    name: 'Qwen Image Remix',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Classic image-to-image: redraw a photo in a new style with a strength slider.',
    tags: ['Strength control', 'Budget'],
    api: 'market',
    kieModel: 'qwen/image-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      { key: 'strength', label: 'Strength', type: 'number', min: 0, max: 1, step: 0.05, default: 0.8, help: 'Higher = further from the source image.' },
      { key: 'guidance_scale', label: 'Guidance', type: 'number', min: 0, max: 20, step: 0.5, default: 2.5, advanced: true, help: 'How strictly to follow the prompt.' },
      { key: 'num_inference_steps', label: 'Steps', type: 'number', min: 2, max: 250, default: 30, advanced: true },
      { ...negativePrompt('blurry, ugly'), help: 'Things to keep out of the result (max 500 chars).' },
      seedField(),
      { key: 'acceleration', label: 'Acceleration', type: 'enum', options: opts('none', 'regular', 'high'), default: 'none', advanced: true },
      { key: 'output_format', label: 'Format', type: 'enum', options: opts('png', 'jpeg'), default: 'png', advanced: true },
      { key: 'enable_safety_checker', label: 'Safety checker', type: 'boolean', default: true, advanced: true },
    ],
    media: [{ key: 'images', api: 'image_url', kind: 'image', label: 'Image to remix', min: 1, max: 1, single: true, help: '≤10MB.' }],
    // price unverified — feed bills 4 credits per megapixel of output; assumes ~1MP.
    pricing: { credits: 4 },
  },

  // ─── Alibaba Wan image ─────────────────────────────────────────────────────
  {
    id: 'wan-2.7-image-pro-edit',
    family: 'wan-image',
    name: 'Wan 2.7 Image Pro Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Higher-quality Wan edits from up to 9 references, when the standard model misses detail.',
    tags: ['9 references', '2K'],
    api: 'market',
    kieModel: 'wan/2-7-image-pro',
    output: 'image',
    promptMax: 5000,
    fields: wanImageFields(['1K', '2K']),
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 9, help: 'Up to 9 images.' }],
    fixed: { n: 1 },
    pricing: { credits: 12 },
    isNew: true,
  },
  {
    id: 'wan-2.7-image-edit',
    family: 'wan-image',
    name: 'Wan 2.7 Image Edit',
    provider: 'Alibaba',
    mode: 'image-to-image',
    bestFor: 'Affordable multi-reference edits and composites from up to 9 images.',
    tags: ['9 references', 'Budget'],
    api: 'market',
    kieModel: 'wan/2-7-image',
    output: 'image',
    promptMax: 5000,
    fields: wanImageFields(['1K', '2K', '4K']),
    media: [{ key: 'images', api: 'input_urls', kind: 'image', label: 'Images to edit', min: 1, max: 9, help: 'Up to 9 images.' }],
    fixed: { n: 1 },
    pricing: { credits: 4.8 },
    isNew: true,
  },

  // ─── Upscale / background removal ─────────────────────────────────────────
  {
    id: 'topaz-image-upscale',
    family: 'topaz',
    name: 'Topaz Image Upscale',
    provider: 'Topaz Labs',
    mode: 'image-to-image',
    bestFor: 'Upscaling photos 2× or 4× for print while restoring real detail.',
    tags: ['Upscale', '4×'],
    api: 'market',
    kieModel: 'topaz/image-upscale',
    output: 'image',
    noPrompt: true,
    fields: [{
      key: 'upscale_factor', label: 'Upscale', type: 'enum', cast: 'string', default: '2',
      options: [{ value: '1', label: '1× (enhance)' }, { value: '2', label: '2×' }, { value: '4', label: '4×' }],
    }],
    media: [{ key: 'images', api: 'image_url', kind: 'image', label: 'Image to upscale', min: 1, max: 1, single: true, help: '≤10MB.' }],
    // price unverified — feed prices by output size (10 up to 2K, 20 at 4K), not by factor;
    // 2× and 4× are charged the 4K price to be safe.
    pricing: { by: 'upscale_factor', table: { '1': 10, '2': 20, '4': 20 } },
  },
  {
    id: 'recraft-crisp-upscale',
    family: 'recraft',
    name: 'Recraft Crisp Upscale',
    provider: 'Recraft',
    mode: 'image-to-image',
    bestFor: 'Sharpening small or soft images for almost nothing before you use them elsewhere.',
    tags: ['Upscale', 'Budget'],
    api: 'market',
    kieModel: 'recraft/crisp-upscale',
    output: 'image',
    noPrompt: true,
    fields: [],
    media: [{ key: 'images', api: 'image', kind: 'image', label: 'Image to upscale', min: 1, max: 1, single: true, help: '≤10MB.' }],
    pricing: { credits: 0.5 },
  },
  {
    id: 'recraft-remove-background',
    family: 'recraft',
    name: 'Recraft Remove Background',
    provider: 'Recraft',
    mode: 'image-to-image',
    bestFor: 'Cutting a product or person out onto a transparent background in one click.',
    tags: ['Background removal', 'Budget'],
    api: 'market',
    kieModel: 'recraft/remove-background',
    output: 'image',
    noPrompt: true,
    fields: [],
    media: [{
      key: 'images', api: 'image', kind: 'image', label: 'Image', min: 1, max: 1, single: true,
      help: 'png/jpg/webp, ≤5MB, 256–4096px, ≤16MP.',
    }],
    pricing: { credits: 1 },
  },
];
