// Text-to-image models on kie.ai (shared ratio/format helpers are also used by
// models-image-edit.ts). Control keys for pre-catalog models are kept as they
// were so saved generations and presets still regenerate correctly.

import type { FieldSpec, MediaSlot, ModelSpec } from './types.ts';
import { negativePrompt, opts, ratio, seedField } from './helpers.ts';

export const RATIOS_WIDE = ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3', '21:9'];
export const RATIOS_NB = ['auto', '1:1', '4:5', '5:4', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9'];
export const RATIOS_FLUX = ['1:1', '4:3', '3:4', '16:9', '9:16'];
/** Flux 2 text-to-image ratios (the image-to-image variants add `auto`). */
export const RATIOS_FLUX2 = ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'];
/** Nano Banana 2 / 2 Lite: adds the extreme 1:4, 4:1, 1:8, 8:1 banners. */
export const RATIOS_NB2 = ['auto', '1:1', '4:5', '5:4', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', '1:4', '4:1', '1:8', '8:1'];
export const RATIOS_IMAGEN = ['1:1', '16:9', '9:16', '3:4', '4:3', 'auto'];
export const RATIOS_GPT_IMAGE_2 = ['auto', '1:1', '3:2', '2:3', '4:3', '3:4', '5:4', '4:5', '16:9', '9:16', '2:1', '1:2', '3:1', '1:3', '21:9', '9:21'];
export const RATIOS_GPT_IMAGE_25 = ['auto', '1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9', '27:16', '16:27', '9:8', '8:9'];
export const RATIOS_GROK = ['1:1', '2:3', '3:2', '16:9', '9:16'];
export const RATIOS_WAN_IMAGE = ['1:1', '16:9', '4:3', '21:9', '3:4', '9:16', '8:1', '1:8'];

export const nbResolution: FieldSpec = {
  key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K', '4K'), default: '1K',
};
export const nbFormat: FieldSpec = {
  key: 'output_format', label: 'Format', type: 'enum', options: [{ value: 'png', label: 'PNG' }, { value: 'jpg', label: 'JPG' }], default: 'png', advanced: true,
};
export const fluxResolution: FieldSpec = {
  key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K'), default: '1K',
};
export const seedreamQuality: FieldSpec = {
  key: 'quality', label: 'Quality', type: 'enum', options: [{ value: 'basic', label: 'Basic' }, { value: 'high', label: 'High' }], default: 'basic',
};

/** `output_format` enum with the doc's exact values (`jpeg`, not `jpg`). */
export const formatField = (values: string[], def: string): FieldSpec => ({
  key: 'output_format', label: 'Format', type: 'enum', default: def, advanced: true,
  options: values.map((value) => ({ value, label: value.toUpperCase() })),
});

/** Market-API `nsfw_checker` toggle (shown in the docs' example bodies). */
export const nsfwChecker = (def = false): FieldSpec => ({
  key: 'nsfw_checker', label: 'Safety checker', type: 'boolean', default: def, advanced: true,
});

/** fal-style `image_size` presets used by Qwen / Seedream 3.0 / Ideogram. */
export const IMAGE_SIZE_OPTIONS = [
  { value: 'square_hd', label: 'Square HD' }, { value: 'square', label: 'Square' },
  { value: 'portrait_4_3', label: 'Portrait 3:4' }, { value: 'portrait_16_9', label: 'Portrait 9:16' },
  { value: 'landscape_4_3', label: 'Landscape 4:3' }, { value: 'landscape_16_9', label: 'Landscape 16:9' },
];

const refImages = (api: string, max: number, mb: number): MediaSlot => ({
  key: 'ref_images', api, kind: 'image', label: 'Reference images', max,
  help: `Optional — up to ${max} images (≤${mb}MB each). Refer to them as Image 1, Image 2… in the prompt.`,
});

const ideogramSpeed: FieldSpec = {
  key: 'rendering_speed', label: 'Rendering', type: 'enum', default: 'BALANCED',
  options: [{ value: 'TURBO', label: 'Turbo' }, { value: 'BALANCED', label: 'Balanced' }, { value: 'QUALITY', label: 'Quality' }],
};

const gptImageResolution: FieldSpec = {
  key: 'resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K', '4K'), default: '1K',
};

const gptBackground = (when?: FieldSpec['when']): FieldSpec => ({
  key: 'background', label: 'Background', type: 'enum', default: 'auto',
  options: [{ value: 'auto', label: 'Auto' }, { value: 'opaque', label: 'Opaque' }, { value: 'transparent', label: 'Transparent' }],
  help: 'Transparent gives a cut-out PNG — good for logos, stickers and product assets.',
  ...(when ? { when } : {}),
});

const wanImageFields = (pro: boolean): FieldSpec[] => [
  ratio('aspect_ratio', RATIOS_WAN_IMAGE),
  {
    key: 'resolution', label: 'Resolution', type: 'enum', default: '2K',
    options: pro ? opts('1K', '2K', '4K') : opts('1K', '2K'),
  },
  {
    key: 'thinking_mode', label: 'Thinking mode', type: 'boolean', default: false,
    help: 'Reasons about the layout before drawing — slower, better for complex scenes.',
  },
  { key: 'watermark', label: 'Watermark', type: 'boolean', default: false, advanced: true },
  seedField(),
];

export const IMAGE_SPECS: ModelSpec[] = [
  // ─── Google — Nano Banana & Imagen 4 ──────────────────────────────────────
  {
    id: 'nano-banana-2',
    family: 'nano-banana',
    name: 'Nano Banana 2',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Everyday photoreal and text-heavy images up to 4K at under half the price of Nano Banana Pro.',
    tags: ['Text rendering', '4K', 'Value', 'Optional refs'],
    api: 'market',
    kieModel: 'nano-banana-2',
    output: 'image',
    promptMax: 20000,
    fields: [
      ratio('aspect_ratio', RATIOS_NB2, 'auto'),
      nbResolution,
      { ...nbFormat, default: 'jpg' },
    ],
    media: [refImages('image_input', 14, 30)],
    pricing: { by: 'resolution', table: { '1K': 8, '2K': 12, '4K': 18 } },
    featured: true,
    isNew: true,
  },
  {
    id: 'nano-banana-pro',
    family: 'nano-banana',
    name: 'Nano Banana Pro',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Photoreal product shots, portraits and posters with crisp, correctly spelled text — up to 4K.',
    tags: ['Text rendering', '4K', 'Photoreal'],
    api: 'market',
    kieModel: 'nano-banana-pro',
    output: 'image',
    promptMax: 10000,
    fields: [ratio('aspectRatio', RATIOS_NB, '1:1'), nbResolution, nbFormat],
    media: [refImages('image_input', 8, 30)],
    pricing: { by: 'resolution', table: { '1K': 18, '2K': 18, '4K': 24 } },
  },
  {
    id: 'nano-banana-2-lite',
    family: 'nano-banana',
    name: 'Nano Banana 2 Lite',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Cheap 1K drafts and social images in any ratio, including ultra-wide 8:1 banners.',
    tags: ['Budget', 'Banners', 'Optional refs'],
    api: 'market',
    kieModel: 'nano-banana-2-lite',
    output: 'image',
    promptMax: 20000,
    fields: [ratio('aspect_ratio', RATIOS_NB2, 'auto')],
    media: [refImages('image_urls', 10, 30)],
    pricing: { credits: 4 },
    isNew: true,
  },
  {
    id: 'nano-banana',
    family: 'nano-banana',
    name: 'Nano Banana',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Quick, low-cost everyday images when you don’t need 2K+ resolution.',
    tags: ['Budget', 'Fast'],
    api: 'market',
    kieModel: 'google/nano-banana',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', ['1:1', '9:16', '16:9', '3:4', '4:3', '3:2', '2:3', '5:4', '4:5', '21:9', 'auto']),
      formatField(['png', 'jpeg'], 'png'),
    ],
    media: [],
    pricing: { credits: 4 },
  },
  {
    id: 'imagen-4-ultra',
    family: 'imagen',
    name: 'Imagen 4 Ultra',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Highest-fidelity Imagen output for hero photos where fine detail and prompt accuracy matter most.',
    tags: ['Photoreal', 'Detail'],
    api: 'market',
    kieModel: 'google/imagen4-ultra',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_IMAGEN, '1:1'), negativePrompt(), { ...seedField(), cast: 'string' }],
    media: [],
    pricing: { credits: 12 },
  },
  {
    id: 'imagen-4',
    family: 'imagen',
    name: 'Imagen 4',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Clean, natural-looking photos and illustrations with good typography at a mid price.',
    tags: ['Photoreal', 'Typography'],
    api: 'market',
    kieModel: 'google/imagen4',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_IMAGEN, '1:1'), negativePrompt(), { ...seedField(), cast: 'string' }],
    media: [],
    pricing: { credits: 8 },
  },
  {
    id: 'imagen-4-fast',
    family: 'imagen',
    name: 'Imagen 4 Fast',
    provider: 'Google',
    mode: 'text-to-image',
    bestFor: 'Fast, cheap Imagen drafts to explore compositions before rendering with Imagen 4 or Ultra.',
    tags: ['Fast', 'Budget'],
    api: 'market',
    kieModel: 'google/imagen4-fast',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspect_ratio', RATIOS_IMAGEN, '16:9'), negativePrompt(), { ...seedField(), cast: 'number' }],
    media: [],
    pricing: { credits: 4 },
  },

  // ─── OpenAI — GPT Image ───────────────────────────────────────────────────
  {
    id: 'gpt-image-2',
    family: 'gpt',
    name: 'GPT Image 2',
    provider: 'OpenAI',
    mode: 'text-to-image',
    bestFor: 'Infographics, UI mocks and dense layouts from long, detailed briefs — with transparent backgrounds.',
    tags: ['Instruction following', 'Layouts', '4K', 'Transparent'],
    api: 'market',
    kieModel: 'gpt-image-2-text-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [
      {
        ...ratio('aspect_ratio', RATIOS_GPT_IMAGE_2, 'auto'),
        help: 'Auto only renders at 1K. 2K drops 5:4, 4:5, 3:1, 1:3, 9:21; 4K also drops 1:1.',
      },
      { ...gptImageResolution, help: '2K/4K need an explicit aspect ratio (not Auto).' },
      gptBackground({ key: 'resolution', in: ['1K'] }),
    ],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    featured: true,
    isNew: true,
  },
  {
    id: 'gpt-image-2.5-flare',
    family: 'gpt',
    name: 'GPT Image 2.5 Flare',
    provider: 'OpenAI',
    mode: 'text-to-image',
    bestFor: 'Posters and key art in unusual ratios (27:16, 9:8) with transparent-background export up to 4K.',
    tags: ['Layouts', '4K', 'Transparent'],
    api: 'market',
    kieModel: 'gpt-image-2-5-flare-text-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [
      { ...ratio('aspect_ratio', RATIOS_GPT_IMAGE_25, 'auto'), help: '27:16, 16:27, 9:8 and 8:9 render at 1K only.' },
      gptImageResolution,
      gptBackground(),
    ],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    isNew: true,
  },
  {
    id: 'gpt-image-2.5-sunburst',
    family: 'gpt',
    name: 'GPT Image 2.5 Sunburst',
    provider: 'OpenAI',
    mode: 'text-to-image',
    bestFor: 'Second GPT Image 2.5 variant — same controls and price as Flare; try it when Flare’s take misses.',
    tags: ['Layouts', '4K', 'Transparent'],
    api: 'market',
    kieModel: 'gpt-image-2-5-sunburst-text-to-image',
    output: 'image',
    promptMax: 20000,
    fields: [
      { ...ratio('aspect_ratio', RATIOS_GPT_IMAGE_25, 'auto'), help: '27:16, 16:27, 9:8 and 8:9 render at 1K only.' },
      gptImageResolution,
      gptBackground(),
    ],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 6, '2K': 10, '4K': 16 } },
    isNew: true,
  },
  {
    id: 'gpt-image-1.5',
    family: 'gpt',
    name: 'GPT Image 1.5',
    provider: 'OpenAI',
    mode: 'text-to-image',
    bestFor: 'Candid, natural photos and instruction-heavy scenes; medium quality is one of the cheapest options.',
    tags: ['Instruction following', 'Budget'],
    api: 'market',
    kieModel: 'gpt-image/1.5-text-to-image',
    output: 'image',
    fields: [
      ratio('aspect_ratio', ['1:1', '2:3', '3:2']),
      { key: 'quality', label: 'Quality', type: 'enum', default: 'medium', options: [{ value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }] },
    ],
    media: [],
    pricing: { by: 'quality', table: { medium: 4, high: 22 } },
  },
  {
    id: 'gpt-4o',
    family: 'gpt',
    name: 'GPT-4o Image',
    provider: 'OpenAI',
    mode: 'text-to-image',
    bestFor: 'Long, conversational briefs with many constraints — infographics, UI mocks, layouts.',
    tags: ['Instruction following', 'Layouts'],
    api: 'gpt4o',
    output: 'image',
    fields: [
      { key: 'size', label: 'Aspect ratio', type: 'enum', options: opts('1:1', '3:2', '2:3'), default: '1:1' },
      // isEnhance / enableFallback are from the older 4o docs and the new market example, not the current legacy schema — unverified.
      { key: 'isEnhance', label: 'Provider prompt enhance', type: 'boolean', default: false, advanced: true },
    ],
    media: [],
    fixed: { enableFallback: false },
    pricing: { credits: 6 },
  },

  // ─── ByteDance — Seedream ─────────────────────────────────────────────────
  {
    id: 'seedream-5-pro',
    family: 'seedream',
    name: 'Seedream 5.0 Pro',
    provider: 'ByteDance',
    mode: 'text-to-image',
    bestFor: 'Polished ad creatives and cinematic scenes from long prompts, with stronger detail than Lite.',
    tags: ['Aesthetic', 'Detail'],
    api: 'market',
    kieModel: 'seedream/5-pro-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', RATIOS_WIDE),
      { key: 'quality', label: 'Quality', type: 'enum', default: 'basic', options: [{ value: 'basic', label: '1K' }, { value: 'high', label: '2K' }] },
      formatField(['png', 'jpeg'], 'png'),
      nsfwChecker(),
    ],
    media: [],
    pricing: { by: 'quality', table: { basic: 7, high: 14 } },
    isNew: true,
  },
  {
    id: 'seedream-5-lite',
    family: 'seedream',
    name: 'Seedream 5.0 Lite',
    provider: 'ByteDance',
    mode: 'text-to-image',
    bestFor: 'Aesthetic marketing visuals up to 4K at one flat low price, whatever the resolution.',
    tags: ['Aesthetic', '4K', 'Budget'],
    api: 'market',
    kieModel: 'seedream/5-lite-text-to-image',
    output: 'image',
    promptMax: 3000,
    fields: [
      ratio('aspect_ratio', RATIOS_WIDE),
      {
        key: 'quality', label: 'Quality', type: 'enum', default: 'basic',
        options: [{ value: 'basic', label: '2K' }, { value: 'high', label: '3K' }, { value: 'ultra', label: '4K' }],
      },
      formatField(['png', 'jpeg'], 'png'),
      nsfwChecker(),
    ],
    media: [],
    pricing: { credits: 5.5 },
    isNew: true,
  },
  {
    id: 'seedream-4.5',
    family: 'seedream',
    name: 'Seedream 4.5',
    provider: 'ByteDance',
    mode: 'text-to-image',
    bestFor: 'Mood-driven, painterly or cinematic scenes and emotional portraits at a low price.',
    tags: ['Aesthetic', 'Budget'],
    api: 'market',
    kieModel: 'seedream/4.5-text-to-image',
    output: 'image',
    promptMax: 3000,
    fields: [ratio('aspectRatio', RATIOS_WIDE), seedreamQuality, nsfwChecker()],
    media: [],
    pricing: { credits: 6.5 },
  },
  {
    id: 'seedream-4.0',
    family: 'seedream',
    name: 'Seedream 4.0',
    provider: 'ByteDance',
    mode: 'text-to-image',
    bestFor: 'Consistent sets of up to 6 related images from one prompt, e.g. a product line or storyboard.',
    tags: ['Multi-image', '4K'],
    api: 'market',
    kieModel: 'bytedance/seedream-v4-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      {
        key: 'image_size', label: 'Output size', type: 'enum', default: 'square_hd',
        options: [
          ...IMAGE_SIZE_OPTIONS,
          { value: 'portrait_3_2', label: 'Portrait 2:3' }, { value: 'landscape_3_2', label: 'Landscape 3:2' },
          { value: 'landscape_21_9', label: 'Landscape 21:9' },
        ],
      },
      { key: 'image_resolution', label: 'Resolution', type: 'enum', options: opts('1K', '2K', '4K'), default: '1K' },
      seedField(),
      nsfwChecker(true),
    ],
    media: [],
    // Studio shows one image per generation, so request exactly one.
    fixed: { max_images: 1 },
    // price unverified — Seedream 4.0 is not in the pricing feed; uses Seedream 4.5's 6.5/image rounded up.
    pricing: { credits: 7 },
  },
  {
    id: 'seedream-3.0',
    family: 'seedream',
    name: 'Seedream 3.0',
    provider: 'ByteDance',
    mode: 'text-to-image',
    bestFor: 'Legacy Seedream look with guidance control, for matching older campaign images.',
    tags: ['Legacy'],
    api: 'market',
    kieModel: 'bytedance/seedream',
    output: 'image',
    promptMax: 5000,
    fields: [
      { key: 'image_size', label: 'Output size', type: 'enum', default: 'square_hd', options: IMAGE_SIZE_OPTIONS },
      { key: 'guidance_scale', label: 'Guidance', type: 'number', min: 1, max: 10, step: 0.1, default: 2.5, advanced: true, help: 'How strictly to follow the prompt.' },
      seedField(),
    ],
    media: [],
    // price unverified — Seedream 3.0 is not in the pricing feed; uses Seedream 4.5's 6.5/image rounded up.
    pricing: { credits: 7 },
  },

  // ─── Black Forest Labs — Flux 2 & Kontext ─────────────────────────────────
  {
    id: 'flux-flex-pro',
    family: 'flux',
    name: 'Flux 2 Pro',
    provider: 'Black Forest Labs',
    mode: 'text-to-image',
    bestFor: 'High-fidelity detail and exact brand colors (hex) at the best quality-per-credit.',
    tags: ['Detail', 'Hex colors', 'Value'],
    api: 'market',
    kieModel: 'flux-2/pro-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspectRatio', RATIOS_FLUX2), fluxResolution, nsfwChecker()],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 5, '2K': 7 } },
    featured: true,
  },
  {
    id: 'flux-flex',
    family: 'flux',
    name: 'Flux 2 Flex',
    provider: 'Black Forest Labs',
    mode: 'text-to-image',
    bestFor: 'Stylized, conceptual and surreal art direction with bold graphic composition.',
    tags: ['Stylized', 'Concept'],
    api: 'market',
    kieModel: 'flux-2/flex-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [ratio('aspectRatio', RATIOS_FLUX2), fluxResolution, nsfwChecker()],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 14, '2K': 24 } },
  },
  {
    id: 'flux-kontext',
    family: 'flux-kontext',
    name: 'Flux Kontext',
    provider: 'Black Forest Labs',
    mode: 'text-to-image',
    bestFor: 'Clean, prompt-faithful scenes in Flux style; pick Max for tougher typography and detail.',
    tags: ['Pro / Max', 'Typography'],
    api: 'kontext',
    output: 'image',
    fields: [
      {
        key: 'kontextModel', api: 'model', label: 'Tier', type: 'enum', default: 'flux-kontext-pro',
        options: [{ value: 'flux-kontext-pro', label: 'Pro' }, { value: 'flux-kontext-max', label: 'Max' }],
      },
      ratio('aspectRatio', ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'], '16:9', 'aspectRatio'),
      { key: 'outputFormat', label: 'Format', type: 'enum', default: 'jpeg', advanced: true, options: [{ value: 'jpeg', label: 'JPEG' }, { value: 'png', label: 'PNG' }] },
      { key: 'promptUpsampling', label: 'Prompt upsampling', type: 'boolean', default: false, advanced: true, help: 'Let the model expand a short prompt.' },
      { key: 'enableTranslation', label: 'Auto-translate prompt', type: 'boolean', default: true, advanced: true, help: 'Kontext only understands English; this translates other languages first.' },
      { key: 'safetyTolerance', label: 'Safety tolerance', type: 'number', min: 0, max: 6, step: 1, default: 2, advanced: true, help: '0 = strictest, 6 = most permissive.' },
      { key: 'watermark', label: 'Watermark', type: 'text', default: '', advanced: true, omitIf: '' },
    ],
    media: [],
    pricing: { by: 'kontextModel', table: { 'flux-kontext-pro': 5, 'flux-kontext-max': 10 } },
  },

  // ─── xAI — Grok Imagine ───────────────────────────────────────────────────
  {
    id: 'grok-imagine-image-2.0',
    family: 'grok',
    name: 'Grok Imagine Image 2.0',
    provider: 'xAI',
    mode: 'text-to-image',
    bestFor: 'Bold, punchy social visuals and memes with Grok’s looser, less filtered style.',
    tags: ['Social', 'Budget'],
    api: 'market',
    kieModel: 'grok-imagine-image-2-0/text-to-image',
    output: 'image',
    fields: [ratio('aspect_ratio', RATIOS_GROK)],
    media: [],
    pricing: { credits: 4 },
    isNew: true,
  },
  {
    id: 'grok-imagine-image',
    family: 'grok',
    name: 'Grok Imagine Image',
    provider: 'xAI',
    mode: 'text-to-image',
    bestFor: 'Several quick variations per run to brainstorm a look; switch on Quality for the final pick.',
    tags: ['Variations', 'Budget'],
    api: 'market',
    kieModel: 'grok-imagine/text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', RATIOS_GROK),
      { key: 'enable_pro', label: 'Quality mode', type: 'boolean', default: false, help: 'Off = faster, on = higher quality (+1 credit).' },
    ],
    media: [],
    pricing: { by: 'enable_pro', table: { false: 4, true: 5 } },
  },

  // ─── Ideogram ─────────────────────────────────────────────────────────────
  {
    id: 'ideogram-v3',
    family: 'ideogram',
    name: 'Ideogram V3',
    provider: 'Ideogram',
    mode: 'text-to-image',
    bestFor: 'Logos, posters and graphic design where the words must be spelled and placed exactly.',
    tags: ['Typography', 'Design', 'Styles'],
    api: 'market',
    kieModel: 'ideogram/v3-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      { key: 'image_size', label: 'Output size', type: 'enum', default: 'square_hd', options: IMAGE_SIZE_OPTIONS },
      ideogramSpeed,
      { key: 'style', label: 'Style', type: 'enum', default: 'AUTO', options: [{ value: 'AUTO', label: 'Auto' }, { value: 'GENERAL', label: 'General' }, { value: 'REALISTIC', label: 'Realistic' }, { value: 'DESIGN', label: 'Design' }] },
      { key: 'expand_prompt', label: 'Magic prompt', type: 'boolean', default: true, advanced: true, help: 'Let Ideogram expand your prompt before generating.' },
      negativePrompt(),
      seedField(),
    ],
    media: [],
    pricing: { by: 'rendering_speed', table: { TURBO: 3.5, BALANCED: 7, QUALITY: 10 } },
  },

  // ─── Alibaba — Qwen & Wan ─────────────────────────────────────────────────
  {
    id: 'qwen3-pro',
    family: 'qwen',
    name: 'Qwen Image 3.0 Pro',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Bilingual (Chinese/English) posters and signage with sharper 2K detail than standard Qwen 3.',
    tags: ['Text rendering', 'Bilingual', '2K'],
    api: 'market',
    kieModel: 'qwen3/pro-text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      fluxResolution,
      ratio('image_size', ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'], '16:9', 'image_size'),
      { key: 'prompt_extend', label: 'Prompt extend', type: 'boolean', default: true, advanced: true, help: 'Let the model enrich a short prompt.' },
      negativePrompt(),
      formatField(['png', 'jpeg'], 'png'),
      seedField(),
      nsfwChecker(),
    ],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 6.4, '2K': 12 } },
    isNew: true,
  },
  {
    id: 'qwen3',
    family: 'qwen',
    name: 'Qwen Image 3.0',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Bilingual text-in-image graphics at a flat low price, same price at 1K or 2K.',
    tags: ['Text rendering', 'Bilingual', 'Budget'],
    api: 'market',
    kieModel: 'qwen3/text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      fluxResolution,
      ratio('image_size', ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '21:9'], '16:9', 'image_size'),
      { key: 'prompt_extend', label: 'Prompt extend', type: 'boolean', default: true, advanced: true, help: 'Let the model enrich a short prompt.' },
      negativePrompt(),
      formatField(['png', 'jpeg'], 'png'),
      seedField(),
      nsfwChecker(),
    ],
    media: [],
    pricing: { credits: 4.8 },
    isNew: true,
  },
  {
    id: 'qwen-image-2.1',
    family: 'qwen',
    name: 'Qwen Image 2.1',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Stickers, icons and cut-out assets with transparent backgrounds, including tall 9:21 ratios.',
    tags: ['Transparent', 'Budget'],
    api: 'market',
    kieModel: 'qwen2-1/text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      ratio('aspect_ratio', ['1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '21:9', '9:21']),
      fluxResolution,
      {
        key: 'background', label: 'Background', type: 'enum', default: 'opaque',
        options: [{ value: 'opaque', label: 'Opaque' }, { value: 'transparent', label: 'Transparent' }],
        help: 'Transparent needs PNG or WebP output.',
      },
      formatField(['png', 'webp', 'jpeg'], 'png'),
      { key: 'enhance_prompt', label: 'Enhance prompt', type: 'boolean', default: true, advanced: true },
      seedField(),
    ],
    media: [],
    pricing: { by: 'resolution', table: { '1K': 4, '2K': 8 } },
  },
  {
    id: 'qwen-image-2',
    family: 'qwen',
    name: 'Qwen Image 2',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Short-prompt (≤800 chars) images with legible Chinese or English text at a fixed price.',
    tags: ['Text rendering'],
    api: 'market',
    kieModel: 'qwen2/text-to-image',
    output: 'image',
    promptMax: 800,
    fields: [
      ratio('image_size', ['1:1', '3:4', '4:3', '9:16', '16:9'], '16:9', 'image_size'),
      formatField(['png', 'jpeg'], 'png'),
      seedField(),
    ],
    media: [],
    pricing: { credits: 5.6 },
  },
  {
    id: 'qwen-image',
    family: 'qwen',
    name: 'Qwen Image',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Tunable open-model output — steps, guidance and negative prompt — billed by megapixel.',
    tags: ['Tunable', 'Budget'],
    api: 'market',
    kieModel: 'qwen/text-to-image',
    output: 'image',
    promptMax: 5000,
    fields: [
      { key: 'image_size', label: 'Output size', type: 'enum', default: 'square_hd', options: IMAGE_SIZE_OPTIONS },
      { key: 'num_inference_steps', label: 'Steps', type: 'number', min: 2, max: 250, default: 30, advanced: true },
      { key: 'guidance_scale', label: 'Guidance', type: 'number', min: 0, max: 20, step: 0.5, default: 2.5, advanced: true, help: 'How strictly to follow the prompt.' },
      { ...negativePrompt(), help: 'Up to 500 characters of things to keep out of the result.' },
      { key: 'acceleration', label: 'Acceleration', type: 'enum', options: opts('none', 'regular', 'high'), default: 'none', advanced: true },
      formatField(['png', 'jpeg'], 'png'),
      { key: 'enable_safety_checker', label: 'Safety checker', type: 'boolean', default: true, advanced: true },
      seedField(),
    ],
    media: [],
    // price unverified — feed lists 4 credits per megapixel; table assumes fal-style sizes
    // (square_hd 1024², square 512², 4:3 1024×768, 16:9 1024×576), rounded up.
    pricing: {
      by: 'image_size',
      table: { square_hd: 4.2, square: 1.1, portrait_4_3: 3.2, landscape_4_3: 3.2, portrait_16_9: 2.4, landscape_16_9: 2.4 },
    },
  },
  {
    id: 'wan-2.7-image-pro',
    family: 'wan-image',
    name: 'Wan 2.7 Image Pro',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Layout-heavy 4K images with strong bilingual text and a reasoning pass for complex scenes.',
    tags: ['4K', 'Text rendering'],
    api: 'market',
    kieModel: 'wan/2-7-image-pro',
    output: 'image',
    promptMax: 5000,
    fields: wanImageFields(true),
    media: [],
    // Studio shows one image per generation, so request exactly one.
    fixed: { n: 1, enable_sequential: false },
    pricing: { credits: 12 },
    isNew: true,
  },
  {
    id: 'wan-2.7-image',
    family: 'wan-image',
    name: 'Wan 2.7 Image',
    provider: 'Alibaba',
    mode: 'text-to-image',
    bestFor: 'Budget 2K images with clean Chinese/English text — Wan 2.7 Pro quality at well under half the price.',
    tags: ['Budget', 'Text rendering'],
    api: 'market',
    kieModel: 'wan/2-7-image',
    output: 'image',
    promptMax: 5000,
    fields: wanImageFields(false),
    media: [],
    // Studio shows one image per generation, so request exactly one.
    fixed: { n: 1, enable_sequential: false },
    pricing: { credits: 4.8 },
    isNew: true,
  },

  // ─── Tongyi-MAI — Z-Image ─────────────────────────────────────────────────
  {
    id: 'z-image',
    family: 'z-image',
    name: 'Z-Image',
    provider: 'Tongyi-MAI',
    mode: 'text-to-image',
    bestFor: 'Fastest, cheapest drafts — test an idea for under a credit before spending more.',
    tags: ['Budget', 'Fast'],
    api: 'market',
    kieModel: 'z-image',
    output: 'image',
    promptMax: 1000,
    fields: [ratio('aspectRatio', RATIOS_FLUX), nsfwChecker(true)],
    media: [],
    pricing: { credits: 0.8 },
  },
];
