/**
 * Style presets: a look you pick once and keep while you write your own
 * prompts. At generate time the preset's description is added to the prompt
 * (see composeStylePrompt), so it works with every model and with Prompt Brain.
 *
 * Image looks describe light, colour and medium, so they also suit video.
 * Video presets describe camera movement, pace and format, so they apply to
 * video models only.
 */

export type PresetKind = 'image' | 'video';

export type StyleCategory =
  | 'light' | 'retro' | 'film' | 'editorial' | 'art'
  | 'camera' | 'pace' | 'format';

export const STYLE_CATEGORIES: Array<{ id: StyleCategory; label: string; kind: PresetKind }> = [
  { id: 'light', label: 'Light & mood', kind: 'image' },
  { id: 'retro', label: 'Retro & eras', kind: 'image' },
  { id: 'film', label: 'Film & camera', kind: 'image' },
  { id: 'editorial', label: 'Editorial', kind: 'image' },
  { id: 'art', label: 'Art & dream', kind: 'image' },
  { id: 'camera', label: 'Camera moves', kind: 'video' },
  { id: 'pace', label: 'Time & pace', kind: 'video' },
  { id: 'format', label: 'Formats', kind: 'video' },
];

export const PRESET_KINDS: Array<{ id: PresetKind; label: string }> = [
  { id: 'image', label: 'Image looks' },
  { id: 'video', label: 'Video' },
];

/** Texture drawn over a style's swatch on the Presets page. */
export type SwatchTexture = 'grain' | 'haze' | 'scanlines' | 'halation' | 'chrome' | 'halftone' | 'flash' | 'none';

/** How a video preset's cover moves, hinting at the camera move or pace. */
export type CoverMotion =
  | 'push' | 'pull' | 'orbit' | 'fly' | 'handheld' | 'rise' | 'whip' | 'vertigo'
  | 'drift' | 'timelapse' | 'stutter' | 'ramp' | 'sway';

export interface StylePreset {
  id: string;
  name: string;
  kind: PresetKind;
  category: StyleCategory;
  /** One line shown on the card. */
  tagline: string;
  /** Three or four words that say what the look is made of. */
  notes: string[];
  /** Added to the user's prompt. Written as visual direction, not a subject. */
  prompt: string;
  /** Aspect ratio that suits the look, applied only if the model offers it. */
  aspect?: string;
  /** CSS background for the card swatch. */
  swatch: string;
  texture: SwatchTexture;
  /** Text colour that reads on the swatch. */
  ink: 'light' | 'dark';
  /** Optional sample output shown instead of the swatch. */
  cover?: string;
  /** Video presets: how the cover moves in previews. */
  motion?: CoverMotion;
  isNew?: boolean;
}

type Draft = Omit<StylePreset, 'kind'>;

const IMAGE_LOOKS: Draft[] = [
  // Light & mood
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'light',
    tagline: 'Low sun, warm skin, long soft shadows',
    notes: ['Backlit', 'Warm amber', 'Lens flare'],
    prompt: 'shot during golden hour, low sun just above the horizon backlighting the subject, warm amber and honey tones, glowing rim light on hair and edges, long soft shadows, gentle lens flare, slightly lifted blacks, natural skin warmth, airy and nostalgic',
    swatch: 'radial-gradient(120% 90% at 78% 18%, #FFE3A1 0%, #F7B267 28%, #E07A5F 58%, #6B3E5E 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/golden-hour.webp',
  },
  {
    id: 'hazy-daydream',
    name: 'Hazy Daydream',
    category: 'light',
    tagline: 'Soft focus, blooming highlights, dreamy fog',
    notes: ['Bloom', 'Pastel', 'Low contrast'],
    prompt: 'dreamy hazy atmosphere, soft diffusion filter with blooming highlights, light fog and airborne haze, washed pastel palette, low contrast, milky lifted shadows, gentle glow around light sources, shallow depth of field, calm ethereal mood',
    swatch: 'linear-gradient(160deg, #F6E7F2 0%, #E6D5F5 35%, #CFE3F2 70%, #F3EBDD 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/hazy-daydream.webp',
    isNew: true,
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    category: 'light',
    tagline: 'Cool twilight with warm windows',
    notes: ['Twilight', 'Cool blue', 'Warm practicals'],
    prompt: 'blue hour twilight just after sunset, deep cobalt sky, cool blue ambient light, warm tungsten practical lights and glowing windows for contrast, calm quiet mood, clean shadows, subtle reflections',
    swatch: 'linear-gradient(180deg, #1B2A57 0%, #2E4A8C 45%, #5C7FC2 75%, #F2A65A 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/blue-hour.webp',
  },
  {
    id: 'neon-noir',
    name: 'Neon Noir',
    category: 'light',
    tagline: 'Rain-slick streets in magenta and teal',
    notes: ['Night', 'Neon', 'Wet reflections'],
    prompt: 'neon noir night scene, magenta and teal neon light spilling across the subject, rain-slick reflective surfaces, deep crushed shadows, atmospheric haze catching the light, high contrast, moody cyberpunk cinema look',
    swatch: 'linear-gradient(135deg, #0B0B1A 0%, #2A0C3D 40%, #D1267A 75%, #1FC7C9 100%)',
    texture: 'halation',
    ink: 'light',
    cover: '/presets/neon-noir.webp',
  },
  {
    id: 'party-flash',
    name: 'Party Flash',
    category: 'light',
    tagline: 'Direct on-camera flash, night-out energy',
    notes: ['Hard flash', 'Red-eye era', 'Candid'],
    prompt: 'direct on-camera flash photo at night, hard frontal flash with bright skin and sharp shadow behind the subject, dark falloff background, slight overexposure on faces, candid party snapshot energy, point-and-shoot camera feel',
    swatch: 'radial-gradient(60% 55% at 50% 45%, #FFFFFF 0%, #F2F2F2 25%, #7A7A86 60%, #0E0E12 100%)',
    texture: 'flash',
    ink: 'dark',
    cover: '/presets/party-flash.webp',
  },
  {
    id: 'overcast-soft',
    name: 'Overcast Soft',
    category: 'light',
    tagline: 'Even, flattering, Nordic calm',
    notes: ['Diffused', 'Muted', 'Quiet'],
    prompt: 'soft overcast daylight, large diffused sky light with no hard shadows, muted cool-neutral palette, gentle contrast, true-to-life colour, quiet Scandinavian editorial calm',
    swatch: 'linear-gradient(180deg, #D9DDE1 0%, #C4CACF 50%, #A7AFB3 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/overcast-soft.webp',
  },

  {
    id: 'candlelit',
    name: 'Candlelit',
    category: 'light',
    tagline: 'Intimate flicker, warm pools of light',
    notes: ['Low light', 'Warm glow', 'Chiaroscuro'],
    prompt: 'lit only by candlelight, warm flickering amber glow falling off quickly into deep shadow, chiaroscuro contrast, soft highlights on faces and surfaces, intimate evening mood, subtle grain, painterly low-light richness',
    swatch: 'radial-gradient(45% 50% at 50% 55%, #FFD08A 0%, #E08A3C 30%, #5A2A14 70%, #140A06 100%)',
    texture: 'halation',
    ink: 'light',
    cover: '/presets/candlelit.webp',
  },

  // Retro & eras
  {
    id: 'y2k',
    name: 'Y2K',
    category: 'retro',
    tagline: 'Chrome, gloss and early-2000s pop',
    notes: ['Chrome', 'Glossy', 'Cyber pink'],
    prompt: 'Y2K aesthetic, early 2000s pop culture look, glossy chrome and iridescent surfaces, bubblegum pink, baby blue and silver palette, frosted translucent plastics, glitter and sparkle accents, bright digital-camera flash, playful futuristic styling',
    swatch: 'linear-gradient(135deg, #FFB3E6 0%, #C9B6FF 30%, #9EE6FF 55%, #E9EEF5 75%, #FF7AC6 100%)',
    texture: 'chrome',
    ink: 'dark',
    cover: '/presets/y2k.webp',
    isNew: true,
  },
  {
    id: '90s-disposable',
    name: '90s Disposable',
    category: 'retro',
    tagline: 'Point-and-shoot film, date stamp nostalgia',
    notes: ['Film grain', 'Flash', 'Slight blur'],
    prompt: 'shot on a 1990s disposable film camera, visible film grain, slightly soft focus, built-in flash with warm falloff, faded colour with green-yellow cast, light leaks at the edges, casual candid framing, nostalgic snapshot',
    swatch: 'linear-gradient(160deg, #F4D58D 0%, #E3A857 35%, #9DB17C 70%, #5E6B4B 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/90s-disposable.webp',
  },
  {
    id: '70s-film',
    name: '70s Film',
    category: 'retro',
    tagline: 'Warm browns, soft grain, sun-faded',
    notes: ['Earthy', 'Faded', 'Warm'],
    prompt: '1970s film photograph, warm earthy palette of burnt orange, mustard and chocolate brown, sun-faded colours, soft grain, gentle vignette, slightly hazy highlights, vintage lifestyle magazine feel',
    swatch: 'linear-gradient(180deg, #E8B04B 0%, #C9702E 40%, #7A4B2A 75%, #3D2A1E 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/70s-film.webp',
  },
  {
    id: 'synthwave',
    name: '80s Synthwave',
    category: 'retro',
    tagline: 'Sunset grids and hot magenta glow',
    notes: ['Retro-future', 'Glow', 'Purple sky'],
    prompt: '1980s synthwave aesthetic, hot magenta and electric purple gradient sky, glowing neon rim light, retro-futuristic mood, soft bloom, subtle scanline texture, chrome highlights, cinematic dusk',
    swatch: 'linear-gradient(180deg, #1A0B3B 0%, #5B1B7A 40%, #E8327B 70%, #FFB347 100%)',
    texture: 'scanlines',
    ink: 'light',
    cover: '/presets/synthwave.webp',
  },
  {
    id: 'vhs',
    name: 'VHS Tape',
    category: 'retro',
    tagline: 'Home-video fuzz, bleeding colour',
    notes: ['Tracking lines', 'Chroma bleed', 'Soft'],
    prompt: 'VHS home video still, soft low-resolution look, colour bleeding and chromatic fringing, horizontal tracking lines and noise, washed highlights, slightly oversaturated reds, late 80s camcorder feel',
    swatch: 'linear-gradient(180deg, #3A4A7A 0%, #7A5A8E 45%, #C46A6A 75%, #2B2B3A 100%)',
    texture: 'scanlines',
    ink: 'light',
    cover: '/presets/vhs.webp',
  },
  {
    id: 'polaroid',
    name: 'Instant Photo',
    category: 'retro',
    tagline: 'Creamy instant film, soft and square',
    notes: ['Square', 'Creamy', 'Low contrast'],
    prompt: 'instant film photograph, creamy muted colours with a cyan-green shadow cast, soft low-contrast tones, slight vignette, gentle chemical imperfections, intimate everyday moment',
    aspect: '1:1',
    swatch: 'linear-gradient(160deg, #EFE8D8 0%, #D6DCC9 40%, #9DB7B0 75%, #6C8A8A 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/polaroid.webp',
  },

  // Film & camera
  {
    id: 'cinematic-35',
    name: 'Cinematic 35mm',
    category: 'film',
    tagline: 'Widescreen frames with a movie grade',
    notes: ['Anamorphic', 'Teal & orange', 'Grain'],
    prompt: 'cinematic film still shot on 35mm, anamorphic widescreen framing, motivated lighting with deep shadows, subtle teal and orange colour grade, fine film grain, shallow depth of field, oval bokeh, feature-film production value',
    aspect: '21:9',
    swatch: 'linear-gradient(90deg, #0F2A33 0%, #1F4B55 40%, #C4773B 80%, #E9A25F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/cinematic-35.webp',
  },
  {
    id: 'portra',
    name: 'Portra Glow',
    category: 'film',
    tagline: 'Kodak Portra 400 skin and pastels',
    notes: ['Warm skin', 'Pastel', 'Fine grain'],
    prompt: 'shot on Kodak Portra 400 film, warm natural skin tones, soft pastel colour rendition, gentle highlight roll-off, fine grain, slightly overexposed airy look, medium-format portrait feel',
    swatch: 'linear-gradient(160deg, #F7D9C4 0%, #EDB9A0 35%, #B9C9B3 70%, #8FA6A0 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/portra.webp',
  },
  {
    id: 'cinestill',
    name: 'CineStill 800T',
    category: 'film',
    tagline: 'Tungsten night film with red halation',
    notes: ['Halation', 'Tungsten', 'Night'],
    prompt: 'shot on CineStill 800T tungsten film at night, red-orange halation glowing around highlights and lights, cool cyan shadows, visible grain, practical street and neon lighting, moody urban night',
    swatch: 'radial-gradient(35% 40% at 30% 35%, #FF6B4A 0%, #B8322A 30%, transparent 60%), linear-gradient(180deg, #0D2230 0%, #123C4A 60%, #0A1A22 100%)',
    texture: 'halation',
    ink: 'light',
    cover: '/presets/cinestill.webp',
    isNew: true,
  },
  {
    id: 'velvia',
    name: 'Velvia Vivid',
    category: 'film',
    tagline: 'Saturated slide film, rich landscapes',
    notes: ['Saturated', 'Deep blues', 'Punchy'],
    prompt: 'shot on Fujifilm Velvia slide film, highly saturated rich colour, deep blues and vivid greens, punchy contrast, crisp detail, dramatic landscape photography',
    swatch: 'linear-gradient(170deg, #0B4F8A 0%, #1C7C54 45%, #E0B32B 80%, #C2411F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/velvia.webp',
  },
  {
    id: 'tri-x',
    name: 'Tri-X Mono',
    category: 'film',
    tagline: 'Gritty black and white reportage',
    notes: ['B&W', 'Heavy grain', 'Contrast'],
    prompt: 'black and white photograph shot on Kodak Tri-X 400, strong grain, deep blacks and bright whites, high contrast, documentary street photography feel, timeless and raw',
    swatch: 'linear-gradient(160deg, #F2F2F2 0%, #9A9A9A 40%, #3A3A3A 75%, #0C0C0C 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/tri-x.webp',
  },

  // Editorial
  {
    id: 'glossy-magazine',
    name: 'Glossy Magazine',
    category: 'editorial',
    tagline: 'High-fashion cover polish',
    notes: ['Beauty light', 'Retouched', 'Bold'],
    prompt: 'high-fashion magazine editorial, polished beauty lighting with a large softbox and subtle rim light, flawless retouched skin, bold confident styling, clean seamless backdrop, crisp detail, luxury print quality',
    aspect: '4:5',
    swatch: 'linear-gradient(150deg, #F6F1EB 0%, #E9D7CB 40%, #C9A48C 75%, #2B211C 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/glossy-magazine.webp',
  },
  {
    id: 'studio-product',
    name: 'Studio Product',
    category: 'editorial',
    tagline: 'Clean e-commerce hero shot',
    notes: ['Seamless', 'Soft shadow', 'Sharp'],
    prompt: 'professional studio product photography, clean seamless background, soft key light with a gentle graduated shadow, controlled reflections, tack-sharp detail, accurate colour, premium commercial catalogue look',
    swatch: 'radial-gradient(70% 60% at 50% 40%, #FFFFFF 0%, #F1F1F3 55%, #D9DADF 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/studio-product.webp',
  },
  {
    id: 'quiet-luxury',
    name: 'Quiet Luxury',
    category: 'editorial',
    tagline: 'Stone, linen and restraint',
    notes: ['Neutral', 'Minimal', 'Natural light'],
    prompt: 'quiet luxury aesthetic, minimalist composition with generous negative space, natural materials like travertine, linen and oak, soft directional window light, warm neutral palette of cream, sand and taupe, refined and understated',
    swatch: 'linear-gradient(160deg, #F4EEE4 0%, #E3D6C3 45%, #C4B39A 80%, #9C8B74 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/quiet-luxury.webp',
  },
  {
    id: 'street-style',
    name: 'Street Style',
    category: 'editorial',
    tagline: 'City candid, fashion-week energy',
    notes: ['Telephoto', 'Candid', 'Urban'],
    prompt: 'street style fashion photography, candid moment on a city sidewalk, telephoto compression with blurred passers-by, natural daylight, confident pose mid-stride, urban textures, contemporary editorial colour',
    aspect: '4:5',
    swatch: 'linear-gradient(160deg, #D8D4CE 0%, #9EA3A8 40%, #4E5A66 75%, #1E232A 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/street-style.webp',
  },

  // Art & dream
  {
    id: 'dreamcore',
    name: 'Dreamcore',
    category: 'art',
    tagline: 'Surreal, nostalgic, a little uncanny',
    notes: ['Surreal', 'Liminal', 'Soft glow'],
    prompt: 'dreamcore aesthetic, surreal nostalgic scene with a slightly uncanny liminal feel, soft glowing light, pastel sky, dreamlike scale and floating elements, gentle haze, memory-like softness',
    swatch: 'linear-gradient(170deg, #BFE3FF 0%, #F5D0F0 45%, #FFF1B8 80%, #B7F0D8 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/dreamcore.webp',
  },
  {
    id: 'claymation',
    name: 'Claymation',
    category: 'art',
    tagline: 'Handmade clay, stop-motion charm',
    notes: ['Clay', 'Fingerprints', 'Miniature'],
    prompt: 'claymation stop-motion style, handmade plasticine characters and sets with visible fingerprints and tool marks, miniature diorama, soft studio lighting, rounded playful forms, saturated friendly colours',
    swatch: 'linear-gradient(150deg, #FFB86B 0%, #FF7F6E 35%, #7FC8A9 70%, #6A8CD6 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/claymation.webp',
  },
  {
    id: 'anime-cel',
    name: 'Anime Cel',
    category: 'art',
    tagline: 'Hand-painted anime film frame',
    notes: ['Cel shading', 'Painted sky', 'Clean lines'],
    prompt: 'hand-drawn anime film still, clean line art with cel shading, lush painted background with dramatic clouds, vibrant but soft colour, warm afternoon light, detailed Japanese animation aesthetic',
    aspect: '16:9',
    swatch: 'linear-gradient(180deg, #7EC8F0 0%, #BFE6F5 45%, #FFE6B0 75%, #8CC98B 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/anime-cel.webp',
  },
  {
    id: 'risograph',
    name: 'Risograph',
    category: 'art',
    tagline: 'Two-colour print with misregistration',
    notes: ['Halftone', 'Pink & blue', 'Print'],
    prompt: 'risograph print illustration, limited two-colour palette of fluorescent pink and blue, visible halftone dots and paper texture, slight colour misregistration, flat graphic shapes, indie zine aesthetic',
    swatch: 'linear-gradient(135deg, #FF5FA2 0%, #FF5FA2 48%, #3D6BFF 52%, #3D6BFF 100%)',
    texture: 'halftone',
    ink: 'light',
    cover: '/presets/risograph.webp',
  },
  {
    id: 'watercolor',
    name: 'Watercolour',
    category: 'art',
    tagline: 'Loose washes on textured paper',
    notes: ['Wet edges', 'Paper grain', 'Soft palette'],
    prompt: 'loose watercolour painting, soft translucent washes with wet bleeding edges, visible cold-press paper texture, delicate pencil underdrawing, limited harmonious palette, generous white space, hand-painted illustration',
    swatch: 'radial-gradient(40% 45% at 35% 40%, #9BC4E2 0%, transparent 70%), radial-gradient(45% 40% at 68% 62%, #F2B5A7 0%, transparent 70%), linear-gradient(180deg, #FBF8F2 0%, #F1ECE2 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/watercolor.webp',
  },

  // More looks, no sample image yet: their swatch and texture stand in.
  {
    id: 'harsh-noon',
    name: 'Harsh Noon',
    category: 'light',
    tagline: 'Overhead sun, graphic hard shadows',
    notes: ['Hard light', 'Deep shadow', 'Saturated'],
    prompt: 'harsh midday sun directly overhead, crisp hard-edged shadows forming graphic shapes, bright saturated colour, deep blue sky, high contrast, bold summer fashion campaign energy',
    swatch: 'linear-gradient(160deg, #2F7DE1 0%, #5FA8F5 35%, #F5E6C8 60%, #E3B23C 100%)',
    texture: 'none',
    ink: 'dark',
    isNew: true,
  },
  {
    id: 'moonlit',
    name: 'Moonlit',
    category: 'light',
    tagline: 'Silver night light and soft mist',
    notes: ['Night', 'Silver blue', 'Mist'],
    prompt: 'lit by a full moon at night, cool silver-blue moonlight, soft low mist hanging in the air, gentle rim light on edges, deep indigo shadows, quiet mysterious calm, fine grain',
    swatch: 'radial-gradient(30% 28% at 70% 25%, #EEF3FF 0%, #9FB3D9 35%, transparent 70%), linear-gradient(180deg, #0E1631 0%, #1D2B52 60%, #0A0F20 100%)',
    texture: 'haze',
    ink: 'light',
    isNew: true,
  },
  {
    id: 'kodachrome',
    name: 'Kodachrome 60s',
    category: 'retro',
    tagline: 'Mid-century slide film, rich reds',
    notes: ['Slide film', 'Rich reds', 'Crisp'],
    prompt: 'shot on 1960s Kodachrome slide film, rich saturated reds and deep blues, warm yellows, crisp fine detail, slightly dense shadows, mid-century travel and lifestyle photograph',
    swatch: 'linear-gradient(160deg, #F2D16B 0%, #D9442B 40%, #1F4E8C 80%, #16243D 100%)',
    texture: 'grain',
    ink: 'light',
    isNew: true,
  },
  {
    id: 'daguerreotype',
    name: 'Daguerreotype',
    category: 'retro',
    tagline: '1800s plate, silvered and still',
    notes: ['Sepia', 'Silver plate', 'Vignette'],
    prompt: '19th-century daguerreotype photograph, silvery sepia monochrome, soft focus falloff, heavy dark vignette, scratches and tarnish on the metal plate, formal still pose, antique museum artefact',
    swatch: 'radial-gradient(70% 60% at 50% 45%, #CDBFA4 0%, #8C7A5E 50%, #2E261C 100%)',
    texture: 'grain',
    ink: 'light',
  },
  {
    id: 'medium-format',
    name: 'Medium Format',
    category: 'film',
    tagline: 'Hasselblad depth and creamy falloff',
    notes: ['80mm', 'Creamy bokeh', 'Detail'],
    prompt: 'shot on a medium-format Hasselblad with an 80mm lens, extraordinary detail, creamy shallow depth of field, smooth tonal gradation, natural colour, refined fine-art portrait quality',
    aspect: '4:5',
    swatch: 'linear-gradient(160deg, #EDE6DA 0%, #C9B8A0 40%, #6E6A5E 80%, #2A2A26 100%)',
    texture: 'grain',
    ink: 'light',
  },
  {
    id: 'infrared',
    name: 'Infrared',
    category: 'film',
    tagline: 'Pink foliage, surreal false colour',
    notes: ['False colour', 'Pink leaves', 'Dark sky'],
    prompt: 'infrared photography, foliage turned candy pink and white, deep dark sky, surreal false-colour palette, glowing highlights, otherworldly landscape feel',
    swatch: 'linear-gradient(170deg, #1C2340 0%, #3E4E86 35%, #F4A6C8 70%, #FFE3EE 100%)',
    texture: 'grain',
    ink: 'light',
    isNew: true,
  },
  {
    id: 'flat-lay',
    name: 'Flat Lay',
    category: 'editorial',
    tagline: 'Top-down, styled and tidy',
    notes: ['Overhead', 'Styled', 'Soft shadow'],
    prompt: 'top-down flat lay composition, carefully arranged objects on a clean textured surface, soft even window light with gentle shadows, balanced negative space, lifestyle brand styling',
    aspect: '1:1',
    swatch: 'linear-gradient(135deg, #F3EDE3 0%, #F3EDE3 50%, #E4D4C0 50%, #D9C3A8 100%)',
    texture: 'grain',
    ink: 'dark',
  },
  {
    id: 'architectural',
    name: 'Architectural',
    category: 'editorial',
    tagline: 'Clean lines, corrected verticals',
    notes: ['Symmetry', 'Tilt-shift', 'Minimal'],
    prompt: 'architectural photography, perfectly corrected vertical lines, strong symmetry and geometry, clean minimal composition, soft directional daylight, crisp material textures, design-magazine quality',
    swatch: 'linear-gradient(90deg, #E9E7E2 0%, #E9E7E2 45%, #B9B6AF 45%, #B9B6AF 55%, #7D7A74 55%, #7D7A74 100%)',
    texture: 'none',
    ink: 'dark',
  },
  {
    id: 'oil-painting',
    name: 'Oil Painting',
    category: 'art',
    tagline: 'Old-master brushwork and glaze',
    notes: ['Impasto', 'Chiaroscuro', 'Canvas'],
    prompt: 'classical oil painting, visible impasto brushstrokes and layered glazes, old-master chiaroscuro lighting, rich earthy pigments, fine canvas texture, museum-quality fine art',
    swatch: 'radial-gradient(50% 55% at 45% 45%, #C79A5A 0%, #7A4A26 45%, #2A1810 100%)',
    texture: 'grain',
    ink: 'light',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    category: 'art',
    tagline: '16-bit sprites and dithered skies',
    notes: ['16-bit', 'Limited palette', 'Dithering'],
    prompt: '16-bit pixel art, crisp square pixels, limited retro game palette, ordered dithering in gradients, clean readable sprites, nostalgic console game scene',
    swatch: 'linear-gradient(180deg, #2B1B5A 0%, #2B1B5A 20%, #4B2F8F 20%, #4B2F8F 40%, #8A4FB8 40%, #8A4FB8 55%, #F28A30 55%, #F28A30 65%, #2E9C6A 65%, #2E9C6A 100%)',
    texture: 'none',
    ink: 'light',
    isNew: true,
  },
  {
    id: 'isometric-3d',
    name: 'Isometric 3D',
    category: 'art',
    tagline: 'Tiny soft-lit worlds in a cube',
    notes: ['Isometric', 'Soft render', 'Miniature'],
    prompt: 'isometric 3D render, miniature diorama on a floating tile, soft global illumination, smooth matte materials, pastel palette, clean edges, playful and tidy',
    aspect: '1:1',
    swatch: 'linear-gradient(150deg, #CDE7FF 0%, #B9C8FF 40%, #FFC9DE 75%, #FFE9B8 100%)',
    texture: 'none',
    ink: 'dark',
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    category: 'art',
    tagline: 'Japanese woodblock print',
    notes: ['Woodblock', 'Flat colour', 'Bold outline'],
    prompt: 'ukiyo-e Japanese woodblock print, bold outlines, flat areas of colour with subtle gradients, Prussian blue and muted vermilion palette, stylised waves and clouds, visible washi paper texture',
    swatch: 'radial-gradient(22% 18% at 72% 26%, #C8553D 0 98%, transparent 100%), radial-gradient(120% 60% at 30% 100%, #1E3559 0%, #2B4C7E 45%, transparent 46%), linear-gradient(180deg, #F1E3C6 0%, #E8D5AE 100%)',
    texture: 'grain',
    ink: 'dark',
  },
];

/**
 * Video presets reuse image-look samples as covers; the cover's motion is what
 * shows the preset (a slow push-in, an orbit, a timelapse…).
 */
const VIDEO_PRESETS: Draft[] = [
  // Camera moves
  {
    id: 'slow-push-in',
    name: 'Slow Push-In',
    category: 'camera',
    tagline: 'Creeping dolly toward the subject',
    notes: ['Dolly in', 'Steady', 'Building tension'],
    prompt: 'camera: slow steady dolly push-in toward the subject, smooth gimbal movement, subject grows in frame over the shot, cinematic tension building, shallow depth of field',
    swatch: 'linear-gradient(90deg, #0F2A33 0%, #1F4B55 40%, #C4773B 80%, #E9A25F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/candlelit.webp',
    motion: 'push',
  },
  {
    id: 'pull-back-reveal',
    name: 'Pull-Back Reveal',
    category: 'camera',
    tagline: 'Start close, reveal the whole world',
    notes: ['Dolly out', 'Reveal', 'Scale'],
    prompt: 'camera: starts tight on a detail then smoothly pulls back to reveal the full scene and its scale, continuous single take, steady motion, epic reveal',
    swatch: 'linear-gradient(170deg, #0B4F8A 0%, #1C7C54 45%, #E0B32B 80%, #C2411F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/overcast-soft.webp',
    motion: 'pull',
  },
  {
    id: 'orbit',
    name: '360 Orbit',
    category: 'camera',
    tagline: 'Circle the subject in one smooth arc',
    notes: ['Orbit', 'Parallax', 'Hero'],
    prompt: 'camera: smooth orbit around the subject in a continuous arc, background parallax sliding behind, subject stays centred and sharp, hero shot',
    swatch: 'radial-gradient(70% 60% at 50% 40%, #FFFFFF 0%, #F1F1F3 55%, #D9DADF 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/studio-product.webp',
    motion: 'orbit',
    isNew: true,
  },
  {
    id: 'fpv-drone',
    name: 'FPV Drone',
    category: 'camera',
    tagline: 'Fast, low, weaving fly-through',
    notes: ['Fly-through', 'Speed', 'Banking'],
    prompt: 'camera: FPV drone flying fast and low through the scene, banking turns and dives, weaving past obstacles, wide-angle lens, exhilarating continuous motion, slight motion blur',
    aspect: '16:9',
    swatch: 'linear-gradient(180deg, #7EC8F0 0%, #3E8FC2 40%, #2F6B3A 75%, #1B3A22 100%)',
    texture: 'none',
    ink: 'light',
    cover: '/presets/velvia.webp',
    motion: 'fly',
    isNew: true,
  },
  {
    id: 'handheld-doc',
    name: 'Handheld Doc',
    category: 'camera',
    tagline: 'Loose, human, in the moment',
    notes: ['Handheld', 'Observational', 'Natural'],
    prompt: 'camera: handheld documentary style, subtle natural shake and breathing, reactive reframing, observational and intimate, natural available light, real-moment authenticity',
    swatch: 'linear-gradient(160deg, #D8D4CE 0%, #9EA3A8 40%, #4E5A66 75%, #1E232A 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/tri-x.webp',
    motion: 'handheld',
  },
  {
    id: 'crane-up',
    name: 'Crane Up',
    category: 'camera',
    tagline: 'Rise above the scene for the finale',
    notes: ['Jib', 'Rising', 'Establishing'],
    prompt: 'camera: smooth crane shot rising upward from ground level to a high angle over the scene, revealing the surroundings, grand establishing move, steady and graceful',
    swatch: 'linear-gradient(180deg, #1B2A57 0%, #2E4A8C 45%, #5C7FC2 75%, #F2A65A 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/blue-hour.webp',
    motion: 'rise',
  },
  {
    id: 'whip-pan',
    name: 'Whip Pan',
    category: 'camera',
    tagline: 'Snap sideways with a blur of energy',
    notes: ['Fast pan', 'Motion blur', 'Energetic'],
    prompt: 'camera: fast whip pan snapping sideways onto the subject, streaking horizontal motion blur during the move, sharp landing, energetic kinetic editing feel',
    swatch: 'linear-gradient(135deg, #0B0B1A 0%, #2A0C3D 40%, #D1267A 75%, #1FC7C9 100%)',
    texture: 'halation',
    ink: 'light',
    cover: '/presets/neon-noir.webp',
    motion: 'whip',
  },
  {
    id: 'dolly-zoom',
    name: 'Dolly Zoom',
    category: 'camera',
    tagline: 'Vertigo warp, background stretches',
    notes: ['Vertigo', 'Unsettling', 'Hitchcock'],
    prompt: 'camera: dolly zoom vertigo effect, camera moves back while zooming in so the subject stays the same size as the background stretches and warps, unsettling dramatic realisation',
    swatch: 'linear-gradient(170deg, #BFE3FF 0%, #F5D0F0 45%, #FFF1B8 80%, #B7F0D8 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/dreamcore.webp',
    motion: 'vertigo',
    isNew: true,
  },

  // Time & pace
  {
    id: 'slow-motion',
    name: 'Slow Motion',
    category: 'pace',
    tagline: '120fps, every detail suspended',
    notes: ['120fps', 'Suspended', 'Graceful'],
    prompt: 'shot in slow motion at 120 frames per second, graceful suspended movement, hair, fabric and particles drifting, smooth fluid motion, crisp detail in every frame',
    swatch: 'radial-gradient(120% 90% at 78% 18%, #FFE3A1 0%, #F7B267 28%, #E07A5F 58%, #6B3E5E 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/golden-hour.webp',
    motion: 'drift',
  },
  {
    id: 'timelapse',
    name: 'Timelapse',
    category: 'pace',
    tagline: 'Hours pass in seconds',
    notes: ['Day to night', 'Streaking clouds', 'Locked-off'],
    prompt: 'timelapse, locked-off camera, hours compressed into seconds, clouds streaking across the sky, light shifting from day to dusk, city lights switching on, people blurring past',
    aspect: '16:9',
    swatch: 'linear-gradient(180deg, #1B2A57 0%, #2E4A8C 45%, #5C7FC2 75%, #F2A65A 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/blue-hour.webp',
    motion: 'timelapse',
  },
  {
    id: 'speed-ramp',
    name: 'Speed Ramp',
    category: 'pace',
    tagline: 'Fast, then slow on the key moment',
    notes: ['Ramp', 'Impact', 'Sports promo'],
    prompt: 'speed ramp, real-time action accelerates then drops into dramatic slow motion at the key moment before snapping back to speed, punchy sports-promo energy',
    swatch: 'linear-gradient(135deg, #111 0%, #333 40%, #E8327B 75%, #FFB347 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/90s-disposable.webp',
    motion: 'ramp',
    isNew: true,
  },
  {
    id: 'stop-motion',
    name: 'Stop-Motion',
    category: 'pace',
    tagline: 'Charming 12fps handmade movement',
    notes: ['12fps', 'Handmade', 'Tactile'],
    prompt: 'stop-motion animation at 12 frames per second, slightly jittery handmade movement, tactile miniature props, subtle frame-to-frame lighting flicker, charming crafted feel',
    swatch: 'linear-gradient(150deg, #FFB86B 0%, #FF7F6E 35%, #7FC8A9 70%, #6A8CD6 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/claymation.webp',
    motion: 'stutter',
  },
  {
    id: 'seamless-loop',
    name: 'Seamless Loop',
    category: 'pace',
    tagline: 'Ends exactly where it starts',
    notes: ['Loop', 'Ambient', 'Calm'],
    prompt: 'seamless looping video, gentle continuous ambient motion, the final frame matches the first frame perfectly, calm hypnotic rhythm, no cuts',
    swatch: 'linear-gradient(160deg, #F6E7F2 0%, #E6D5F5 35%, #CFE3F2 70%, #F3EBDD 100%)',
    texture: 'haze',
    ink: 'dark',
    cover: '/presets/hazy-daydream.webp',
    motion: 'sway',
  },

  // Formats
  {
    id: 'movie-trailer',
    name: 'Movie Trailer',
    category: 'format',
    tagline: 'Epic, graded, blockbuster weight',
    notes: ['Anamorphic', 'Dramatic', 'Epic'],
    prompt: 'blockbuster movie trailer shot, anamorphic widescreen, dramatic motivated lighting, teal and orange grade, atmospheric haze, slow deliberate camera move, epic scale and tension',
    aspect: '21:9',
    swatch: 'linear-gradient(90deg, #0F2A33 0%, #1F4B55 40%, #C4773B 80%, #E9A25F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/cinematic-35.webp',
    motion: 'pull',
  },
  {
    id: 'music-video',
    name: 'Music Video',
    category: 'format',
    tagline: 'Neon, rhythm and bold moves',
    notes: ['Stylised', 'Rhythmic', 'Coloured light'],
    prompt: 'stylised music video shot, bold coloured lighting and haze, rhythmic camera movement on the beat, confident performance, glossy high-contrast grade',
    swatch: 'linear-gradient(180deg, #1A0B3B 0%, #5B1B7A 40%, #E8327B 70%, #FFB347 100%)',
    texture: 'scanlines',
    ink: 'light',
    cover: '/presets/synthwave.webp',
    motion: 'handheld',
  },
  {
    id: 'ugc-selfie',
    name: 'UGC Selfie',
    category: 'format',
    tagline: 'Vertical, phone-in-hand, talking to camera',
    notes: ['9:16', 'Front camera', 'Authentic'],
    prompt: 'vertical smartphone selfie video, arm-length front camera, person talking directly to camera, natural handheld sway, casual real-home setting, authentic social media UGC feel',
    aspect: '9:16',
    swatch: 'radial-gradient(60% 55% at 50% 45%, #FFFFFF 0%, #F2F2F2 25%, #7A7A86 60%, #0E0E12 100%)',
    texture: 'flash',
    ink: 'dark',
    cover: '/presets/party-flash.webp',
    motion: 'handheld',
    isNew: true,
  },
  {
    id: 'product-turntable',
    name: 'Product Turntable',
    category: 'format',
    tagline: 'Slow spin on a clean studio set',
    notes: ['Turntable', 'Seamless', 'E-commerce'],
    prompt: 'product slowly rotating on a turntable, clean seamless studio background, soft key light with moving reflections gliding across the surface, sharp detail, premium commercial',
    aspect: '1:1',
    swatch: 'radial-gradient(70% 60% at 50% 40%, #FFFFFF 0%, #F1F1F3 55%, #D9DADF 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/studio-product.webp',
    motion: 'orbit',
  },
  {
    id: 'fashion-film',
    name: 'Fashion Film',
    category: 'format',
    tagline: 'Slow, sensual, editorial motion',
    notes: ['Editorial', 'Fabric motion', 'Poised'],
    prompt: 'high-fashion film, poised slow movement, fabric flowing, polished beauty lighting, elegant slow camera glide, luxury editorial grade',
    aspect: '9:16',
    swatch: 'linear-gradient(150deg, #F6F1EB 0%, #E9D7CB 40%, #C9A48C 75%, #2B211C 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/glossy-magazine.webp',
    motion: 'drift',
  },
  {
    id: 'nature-doc',
    name: 'Nature Doc',
    category: 'format',
    tagline: 'Long-lens wildlife, patient framing',
    notes: ['Telephoto', 'Patient', 'Natural'],
    prompt: 'nature documentary footage, long telephoto lens, patient locked-off framing with slow subtle pans, natural light, rich detail, calm observational wildlife filmmaking',
    aspect: '16:9',
    swatch: 'linear-gradient(170deg, #0B4F8A 0%, #1C7C54 45%, #E0B32B 80%, #C2411F 100%)',
    texture: 'grain',
    ink: 'light',
    cover: '/presets/velvia.webp',
    motion: 'sway',
  },
  {
    id: 'anime-action',
    name: 'Anime Action',
    category: 'format',
    tagline: 'Dynamic cuts, speed lines, impact',
    notes: ['Speed lines', 'Impact frames', 'Dynamic'],
    prompt: 'anime action sequence, dynamic sweeping camera, speed lines and impact frames, dramatic foreshortening, bold cel-shaded motion, painted sky background',
    aspect: '16:9',
    swatch: 'linear-gradient(180deg, #7EC8F0 0%, #BFE6F5 45%, #FFE6B0 75%, #8CC98B 100%)',
    texture: 'none',
    ink: 'dark',
    cover: '/presets/anime-cel.webp',
    motion: 'whip',
  },
  {
    id: 'asmr-macro',
    name: 'ASMR Macro',
    category: 'format',
    tagline: 'Extreme close-ups, slow and tactile',
    notes: ['Macro', 'Texture', 'Satisfying'],
    prompt: 'extreme macro close-up, slow satisfying tactile motion, textures in sharp detail, very shallow depth of field, soft diffused light, calm ASMR product video',
    swatch: 'linear-gradient(160deg, #F4EEE4 0%, #E3D6C3 45%, #C4B39A 80%, #9C8B74 100%)',
    texture: 'grain',
    ink: 'dark',
    cover: '/presets/quiet-luxury.webp',
    motion: 'push',
    isNew: true,
  },
];

export const STYLE_PRESETS: StylePreset[] = [
  ...IMAGE_LOOKS.map((s): StylePreset => ({ ...s, kind: 'image' })),
  ...VIDEO_PRESETS.map((s): StylePreset => ({ ...s, kind: 'video' })),
];

export function getStyle(id: string | null | undefined): StylePreset | undefined {
  return id ? STYLE_PRESETS.find((s) => s.id === id) : undefined;
}

/** Image looks suit any output; video presets describe motion, so only video. */
export function styleAppliesTo(style: StylePreset, output: string): boolean {
  return style.kind === 'image' || output === 'video';
}

/** The prompt sent to the model: the user's words first, then the style's look. */
export function composeStylePrompt(prompt: string, styleId: string | null | undefined): string {
  const style = getStyle(styleId);
  if (!style) return prompt;
  const base = prompt.trim().replace(/[.\s]+$/, '');
  const label = style.kind === 'video' ? 'Shot' : 'Style';
  return base ? `${base}. ${label}: ${style.prompt}.` : `${style.prompt}.`;
}
