// Bundles the chat panel (mcp-app/src) into one self-contained HTML string at
// supabase/functions/mcp/ui.gen.ts, which the MCP server serves as its
// ui:// resource. Run `npm run build:mcp-ui` after changing mcp-app/, then
// redeploy the `mcp` function.
//
// Self-contained on purpose: MCP Apps hosts sandbox the panel and only allow the
// domains in its CSP, so all JS and CSS are inlined.

import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../supabase/functions/mcp/ui.gen.ts');
const logo = readFileSync(join(here, 'logo.txt'), 'utf8').trim();

const result = await build({
  entryPoints: [join(here, 'src/main.tsx')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2020', 'safari15'],
  jsx: 'automatic',
  outdir: 'out',
  write: false,
  legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"', LOGO_DATA_URI: JSON.stringify(logo) },
  logLevel: 'warning',
});

const js = result.outputFiles.find((f) => f.path.endsWith('.js')).text.replace(/<\/script/gi, '<\\/script');
const css = result.outputFiles.find((f) => f.path.endsWith('.css'))?.text ?? '';

const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Oltaflock Studio</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${js}</script>
</body>
</html>`;

writeFileSync(out, `// GENERATED by mcp-app/build.mjs: do not edit. Source: mcp-app/src.\n\nexport const STUDIO_HTML = ${JSON.stringify(html)};\n`);
console.log(`Wrote ${out} (${(html.length / 1024).toFixed(0)} KB)`);
